// Pessoas, de A mulher samaritana a Gideão. Formato em reescrita-pessoas.mjs.
export const PESSOAS_A = {
  'A mulher samaritana': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Uma mulher de Samaria que encontrou Jesus num poço, no meio do dia, e saiu dali chamando a cidade inteira.',
    quem: 'Uma mulher da cidade de Sicar, na Samaria. Ela vai buscar água no poço por volta do meio-dia. Ali encontra Jesus, que pede água e puxa conversa. No fim, Jesus diz com todas as letras que é o Messias, e ela corre pra cidade chamando todo mundo pra conhecê-lo.',
    onde: 'João 4.',
    deus: 'Judeus e samaritanos não se falavam, e um mestre judeu conversando sozinho com uma mulher samaritana quebrava duas regras de uma vez. Jesus quebra as duas pra oferecer a ela água viva, uma vida que mata a sede de verdade.\n\nFoi pra essa mulher, e não pra um líder religioso, que Jesus disse uma das frases mais importantes sobre adoração: Deus é Espírito, e quem o adora precisa adorar em espírito e em verdade (João 4.24).',
    erros: 'Jesus menciona que ela teve cinco maridos e que o homem com quem vivia não era seu marido. O texto não conta por quê. Ela pode ter ficado viúva, ter sido abandonada ou ter feito escolhas erradas, e a Bíblia não explica. O que fica claro é que Jesus conhecia a história inteira dela e mesmo assim se ofereceu a ela.',
  },
  'Abel': {
    sub: 'Início da história',
    resumo: 'Segundo filho de Adão e Eva. Ofereceu a Deus o melhor do rebanho, com fé, e foi morto pelo próprio irmão.',
    quem: 'Segundo filho de Adão e Eva, pastor de ovelhas. Ele oferece a Deus as primeiras e melhores crias do rebanho. Deus aceita a oferta dele e não aceita a do irmão, Caim. Caim fica furioso e mata Abel. É a primeira morte contada na Bíblia.',
    onde: 'Gênesis 4.1-10; citado em Mateus 23.35 e Hebreus 11.4.',
    deus: 'Hebreus 11.4 explica que Abel ofereceu um sacrifício melhor pela fé. Deus olhou pro coração de quem ofereceu, e a oferta mostrava esse coração.\n\nO mesmo texto diz que Abel, mesmo morto, ainda fala. E Hebreus 12.24 compara o sangue dele com o de Jesus: o sangue de Abel clamava por vingança, e o de Jesus perdoa gratuitamente.',
  },
  'Abraão': {
    sub: 'Patriarcas',
    resumo: 'Deus o chamou pra deixar tudo e ir pra uma terra que ele nem conhecia. Virou exemplo de quem confia na promessa antes de ver.',
    quem: 'Abraão morava em Ur, na Mesopotâmia, quando Deus o chamou pra deixar a própria terra e ir pra um lugar que ainda ia mostrar. Ele foi. Dele nasceu o povo de Israel, e com ele Deus fez a aliança que atravessa o resto da Bíblia. O Novo Testamento o apresenta como modelo de fé: alguém que confiou na promessa antes de vê-la cumprida.',
    onde: 'Gênesis 12-25; citado em Romanos 4, Gálatas 3 e Hebreus 11.8-19.',
    deus: 'Deus toma a iniciativa. Chama e abençoa Abraão sem que ele tenha feito nada pra merecer. E cumpre a promessa quando, pelas contas humanas, já não dava mais tempo: Isaque nasce quando Abraão e Sara já eram bem idosos.\n\nEm Gênesis 15, na cerimônia da aliança, só Deus passa entre as partes dos animais. Naquele tempo, quem passava ali se comprometia a cumprir o acordo. Deus assume o compromisso sozinho.',
    erros: 'Por medo, Abraão mentiu duas vezes dizendo que Sara era só sua irmã, e a colocou em risco. E, depois de dez anos em Canaã sem filhos, aceitou a proposta de Sara e teve um filho com Hagar, a serva dela.',
  },
  'Absalão': {
    sub: 'Reino de Israel · por volta de 1000 a.C.',
    resumo: 'Filho de Davi, bonito e ambicioso. Vingou a irmã, se revoltou contra o pai e morreu tentando tomar o trono.',
    quem: 'Terceiro filho de Davi, famoso pela beleza e pelo cabelo. Quando o meio-irmão Amnom violenta Tamar, irmã de Absalão, e Davi não faz nada, Absalão espera dois anos e manda matar Amnom. Foge, volta, faz as pazes com o pai só por fora e passa anos conquistando o povo na porta da cidade. Até que lidera uma revolta e expulsa Davi de Jerusalém. Na fuga, fica pendurado pelos cabelos nos galhos de uma árvore e é morto por Joabe e seus homens, mesmo com Davi tendo pedido que tratassem o filho com bondade.',
    onde: '2 Samuel 13-19.',
    deus: 'Nessa história Deus quase não aparece agindo diretamente. O que se vê é o efeito em cadeia do pecado dentro de uma família: a omissão de Davi diante do crime contra Tamar e a ambição do filho. Natã já tinha avisado Davi que a espada não se afastaria da casa dele (2 Samuel 12.10).\n\nQuando Absalão morre, Davi chora: meu filho Absalão, quem me dera ter morrido no seu lugar (2 Samuel 18.33). É uma das cenas de dor de pai mais honestas da Bíblia.',
    erros: 'Mandou matar o meio-irmão, liderou uma rebelião armada contra o próprio pai, que era o rei escolhido por Deus, e desonrou em público as mulheres do palácio de Davi pra mostrar que tinha tomado o poder (2 Samuel 16.22).',
  },
  'Acabe': {
    sub: 'Reino dividido · séc. IX a.C.',
    resumo: 'Rei de Israel casado com Jezabel. Viu Deus responder com fogo no monte Carmelo e mesmo assim não mudou.',
    quem: 'Rei de Israel, filho de Onri, casado com Jezabel, uma princesa fenícia. A Bíblia resume o reinado dele sem rodeios: fez o que o Senhor reprova, mais do que todos os reis antes dele (1 Reis 16.30). Com ele e a esposa, o culto a Baal vira religião oficial, e isso leva ao confronto com o profeta Elias no monte Carmelo. Morre numa batalha contra a Síria, atingido por uma flecha atirada a esmo.',
    onde: '1 Reis 16-22.',
    deus: 'No Carmelo, Deus manda fogo do céu diante do povo e dos profetas de Baal. O povo acreditava que Baal controlava a chuva e o fogo, e Deus mostra quem de fato manda.\n\nDepois vem a história de Nabote. Acabe quer a vinha dele, fica emburrado quando Nabote se recusa a vender e deixa Jezabel armar a morte do homem. Nem um milagre daquele tamanho mudou um coração que já tinha escolhido o que era conveniente. Deus manda Elias anunciar o julgamento sobre a família de Acabe (1 Reis 21.17-24).',
    erros: 'Transformou o culto a Baal em religião do reino, casou com Jezabel mesmo sendo proibido fazer aliança com povos que adoravam ídolos e deixou Nabote ser morto com testemunhas falsas pra ficar com a vinha dele (1 Reis 21).',
  },
  'Adão': {
    sub: 'Início da história',
    resumo: 'O primeiro ser humano segundo Gênesis. Feito à imagem de Deus, desobedeceu, e Deus foi atrás dele.',
    quem: 'Segundo Gênesis 1-2, Adão é o primeiro ser humano, formado do pó da terra e feito à imagem de Deus. Deus o coloca no jardim do Éden pra cuidar da criação, dá a ele Eva como companheira e uma única proibição: não comer do fruto de uma árvore. A desobediência dele marca a entrada do pecado na história e afeta tudo o que vem depois.',
    onde: 'Gênesis 1-5; citado em Romanos 5.12-21 e 1 Coríntios 15.21-22 e 15.45.',
    deus: 'Deus cria por bondade e dá ao ser humano dignidade, trabalho e liberdade de verdade, inclusive a liberdade de dizer não.\n\nDepois da queda, Deus vai atrás de Adão e Eva, que tinham se escondido. Pergunta onde eles estão, faz roupas pra eles e, no meio do julgamento, já promete um descendente que vai esmagar a serpente (Gênesis 3.15). A santidade de Deus e a vontade dele de buscar quem se escondeu aparecem juntas.',
    erros: 'Comeu do fruto proibido mesmo com a ordem clara de Deus e, quando foi questionado, jogou a culpa em Eva.',
  },
  'Ana mãe de Samuel': {
    sub: 'Tempo dos juízes',
    resumo: 'Uma mulher que não conseguia ter filhos e abriu o coração diante de Deus. O filho que ela pediu foi Samuel.',
    quem: 'Ana era uma das duas esposas de Elcana. Não conseguia ter filhos, e todo ano era provocada pela outra esposa, Penina, que tinha. No santuário de Siló, ora com tanta angústia, mexendo os lábios sem som, que o sacerdote Eli acha que ela está bêbada. Ana promete que, se tiver um filho, vai entregá-lo ao serviço de Deus. Samuel nasce, e ela cumpre a promessa.',
    onde: '1 Samuel 1-2.',
    deus: 'O texto diz que o Senhor não tinha permitido que ela tivesse filhos (1 Samuel 1.6) e depois que o Senhor se lembrou dela (1 Samuel 1.19). Pra Bíblia, a espera e a resposta estão nas mãos de Deus.\n\nA oração de Ana depois do nascimento (1 Samuel 2.1-10) celebra um Deus que derruba os orgulhosos e levanta os humildes. Uns mil anos depois, Maria canta algo muito parecido em Lucas 1. Duas mães, a mesma confiança.',
  },
  'Ananias de Damasco': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Um discípulo quase desconhecido que Deus mandou visitar Saulo, o maior perseguidor dos cristãos.',
    quem: 'Um seguidor de Jesus que morava em Damasco e só aparece nesta história. Numa visão, Deus manda ele procurar Saulo de Tarso, que estava cego havia três dias depois de encontrar Jesus na estrada. Ananias tem medo, e com razão: Saulo era conhecido por perseguir cristãos. Mesmo assim vai, coloca as mãos sobre ele, Saulo volta a enxergar e é batizado.',
    onde: 'Atos 9.10-19. Não confunda com o Ananias de Atos 5, marido de Safira.',
    deus: 'Deus escolhe alguém sem fama nenhuma pra um papel decisivo: receber e impor as mãos sobre quem viria a ser o apóstolo Paulo. Ananias hesita, fala do medo com sinceridade e obedece, contra todo instinto de se proteger.',
    erros: 'Hesitou diante da ordem de Deus e lembrou a ele tudo o que Saulo tinha feito antes de obedecer. Deus ouviu e explicou o plano (Atos 9.13-16).',
  },
  'André': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Irmão de Pedro. Quase sempre nos bastidores, e sempre levando alguém até Jesus.',
    quem: 'Pescador da Galileia, irmão de Simão Pedro. Antes de seguir Jesus, era discípulo de João Batista. Segundo o evangelho de João, foi o primeiro a levar outra pessoa até Jesus: o próprio irmão. Fez parte dos doze apóstolos, mas aparece pouco, quase sempre atrás de Pedro, Tiago e João.',
    onde: 'Mateus 4 e 10; Marcos 1, 3 e 13; Lucas 6; João 1, 6 e 12; Atos 1.',
    deus: 'André aparece em gestos pequenos que aproximam pessoas de Jesus. É ele quem encontra o menino com os pães e os peixes antes da multiplicação (João 6.8-9) e quem leva a Jesus alguns gregos que queriam conhecê-lo (João 12.20-22).\n\nO papel dele no grupo era menos de destaque e mais de apresentar gente a Jesus. Deus usa muito esse tipo de pessoa.',
  },
  'Apolo': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Pregador talentoso que aceitou ser corrigido por um casal da igreja e cresceu com isso.',
    quem: 'Judeu de Alexandria, bom de palavra e conhecedor das Escrituras. Chega a Éfeso falando de Jesus com entusiasmo, mas só conhecia o batismo de João. Priscila e Áquila chamam Apolo em particular e explicam o caminho de Deus com mais clareza. Depois ele vai pra Acaia, a região de Corinto, onde Deus o usa pra fortalecer a igreja.',
    onde: 'Atos 18.24-28; citado em 1 Coríntios 1, 3 e 16 e em Tito 3.13.',
    deus: 'Apolo já era um pregador reconhecido e mesmo assim aceitou ser corrigido, em particular, por um casal da igreja. Talento sem disposição pra continuar aprendendo não leva longe.\n\nEm Corinto, a igreja começou a se dividir em torcidas: uns eram de Paulo, outros de Apolo. Paulo corrige isso lembrando que ele plantou, Apolo regou, mas quem fez crescer foi Deus (1 Coríntios 3.6).',
  },
  'Arão': {
    sub: 'Êxodo e deserto',
    resumo: 'Irmão de Moisés e primeiro sumo sacerdote de Israel. Fez o bezerro de ouro, e mesmo assim Deus continuou usando sua família.',
    quem: 'Irmão mais velho de Moisés e irmão de Miriã. Deus o escolhe pra falar por Moisés diante do faraó, porque Moisés dizia ter dificuldade pra falar. Arão se torna o primeiro sumo sacerdote de Israel, e os sacerdotes seguintes vêm da família dele. Só que, enquanto Moisés está no monte Sinai recebendo a lei, Arão cede à pressão do povo e faz o bezerro de ouro.',
    onde: 'Êxodo 4-40; Levítico 8-10; Números 12 e 20.22-29.',
    deus: 'Pouco depois do bezerro de ouro, Deus confirma Arão e sua família como sacerdotes. Deus leva a sério o que aconteceu e, mesmo assim, restaura e continua usando quem falhou feio.\n\nAs leis de sacrifício de Levítico, entregues justamente à família de Arão, mostram outra coisa: um povo que acabou de fazer um ídolo continua precisando de alguém que o aproxime de um Deus santo.',
    erros: 'Fez o bezerro de ouro pro povo adorar e, quando Moisés o confrontou, diminuiu a própria culpa dizendo que só jogou o ouro no fogo e dali saiu o bezerro (Êxodo 32.24). Também se juntou a Miriã pra criticar Moisés por causa da esposa dele, uma mulher cuxita (Números 12).',
  },
  'Barnabé': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'O apelido dele quer dizer encorajador. Apostou em Paulo quando ninguém confiava nele, e depois em Marcos.',
    quem: 'Levita de Chipre. O apelido Barnabé quer dizer encorajador. Foi um dos primeiros a vender o que tinha pra ajudar a igreja de Jerusalém. Quando Paulo se converteu e a igreja ainda tinha medo dele, foi Barnabé quem o apresentou aos apóstolos. Depois viraram parceiros nas primeiras viagens missionárias.',
    onde: 'Atos 4, 9 e 11-15; citado em 1 Coríntios 9.6, Gálatas 2 e Colossenses 4.10.',
    deus: 'Barnabé arriscou a própria reputação por outra pessoa mais de uma vez. Primeiro com Paulo, depois com João Marcos, a quem quis dar uma segunda chance mesmo com Paulo discordando. Anos depois, o próprio Paulo reconheceu o valor de Marcos (2 Timóteo 4.11).\n\nA graça que a igreja recebe de Deus aparece no jeito como os irmãos tratam uns aos outros.',
    erros: 'Em Antioquia, acompanhou Pedro quando ele passou a evitar os cristãos não judeus pra agradar um grupo vindo de Jerusalém. Paulo chamou isso de hipocrisia e confrontou Pedro na frente de todos (Gálatas 2.11-14).',
  },
  'Boaz': {
    sub: 'Tempo dos juízes',
    resumo: 'Fazendeiro de Belém que protegeu Rute e Noemi e casou com Rute. Virou bisavô do rei Davi.',
    quem: 'Dono de terras em Belém e parente de Elimeleque, o marido já falecido de Noemi. Primeiro, Boaz deixa Rute colher nos campos dele e manda os trabalhadores deixarem espigas cair de propósito pra ela. Depois assume o papel de resgatador previsto na lei de Israel: casa com Rute e preserva o nome e a terra da família de Noemi.',
    onde: 'Rute 2-4; citado em Mateus 1.5.',
    deus: 'Boaz vai além do que a lei exigia e assume em público o compromisso de resgatar a família, mesmo havendo outro parente com prioridade. Deus cuidou de uma família em crise por meio de gente comum agindo com integridade no dia a dia.\n\nBoaz se torna bisavô de Davi e entra na genealogia de Jesus. Atos de bondade que pareciam pequenos faziam parte de uma história muito maior.',
  },
  'Caim': {
    sub: 'Início da história',
    resumo: 'Primeiro filho de Adão e Eva. Deus o avisou antes do crime, e mesmo assim ele matou o irmão.',
    quem: 'Primeiro filho de Adão e Eva, agricultor. Ele oferece a Deus parte da colheita. Quando a oferta dele não é aceita e a do irmão Abel é, Caim fica furioso, em vez de olhar pro próprio coração. Convida Abel pro campo e ali o mata. É o primeiro assassino da Bíblia e também o primeiro a construir uma cidade.',
    onde: 'Gênesis 4; citado em Hebreus 11.4, 1 João 3.12 e Judas 11.',
    deus: 'Antes do crime, Deus conversa com Caim e avisa: o pecado está à sua espera e deseja destruí-lo, mas está na sua mão o poder de dominá-lo (Gênesis 4.7). A escolha ainda estava nas mãos dele.\n\nDepois do assassinato vem o castigo, e junto vem um sinal de proteção sobre Caim, pra que ninguém o matasse. Mesmo o primeiro homicida continua sob o cuidado de Deus.',
    erros: 'Matou o próprio irmão, cheio de raiva, e, quando Deus perguntou por Abel, desconversou: por acaso eu sou responsável pelo meu irmão? (Gênesis 4.9).',
  },
  'Calebe': {
    sub: 'Conquista de Canaã',
    resumo: 'Um dos espiões que confiaram em Deus quando o resto do povo teve medo. Aos 85 anos, pediu a parte mais difícil da terra.',
    quem: 'Da tribo de Judá, foi um dos doze espiões que Moisés mandou conhecer Canaã. Dez voltaram assustados e espalharam medo. Só Calebe e Josué disseram que, com Deus, dava pra entrar. Por essa confiança, foram os únicos da geração deles que entraram na terra prometida.',
    onde: 'Números 13-14; Josué 14-15.',
    deus: 'Deus cumpre, décadas depois, o que tinha prometido a Calebe. Aos oitenta e cinco anos, ele pede a região mais difícil de conquistar e diz que continua tão forte quanto no dia em que Moisés o enviou (Josué 14.11).\n\nDeus não esquece uma promessa, e a fé de Calebe não perdeu força com o tempo. A Bíblia diz que ele continuou fiel ao Senhor (Números 32.12).',
  },
  'Cornélio': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Um oficial romano que buscava a Deus. Na casa dele, a igreja se abriu de vez pros povos não judeus.',
    quem: 'Centurião do exército romano em Cesareia. Não era judeu, mas respeitava a Deus, ajudava os pobres e orava com frequência. Um anjo manda ele chamar Pedro, e esse encontro marca a abertura da igreja pros povos não judeus.',
    onde: 'Atos 10-11.',
    deus: 'Enquanto os mensageiros de Cornélio estão a caminho, Pedro tem uma visão: um lençol com animais considerados impuros e a ordem de não chamar de impuro o que Deus purificou. Era a preparação pra ele entrar na casa de um não judeu, coisa que a tradição judaica evitava.\n\nNa casa de Cornélio, o Espírito Santo desce sobre todos enquanto Pedro ainda está falando. Pedro conclui que Deus não trata as pessoas com diferença (Atos 10.34). A boa notícia é pra todos os povos.',
  },
  'Daniel': {
    sub: 'Exílio · séc. VI a.C.',
    resumo: 'Levado jovem pra Babilônia, manteve a fé no meio de um império estrangeiro e foi salvo da cova dos leões.',
    quem: 'Jovem judeu levado prisioneiro pra Babilônia. Por sua sabedoria e integridade, chegou a cargos altos no governo de impérios diferentes. É lembrado por recusar a comida do rei, por interpretar sonhos e por sair vivo da cova dos leões.',
    onde: 'Livro de Daniel.',
    deus: 'Deus sustenta quem se recusa a abrir mão da fé mesmo sob pressão, como Daniel na cova dos leões e seus amigos na fornalha. As visões do livro mostram que os impérios humanos passam, e que no fim o reino de Deus vai prevalecer sobre todos eles.\n\nDaniel também trabalhou com excelência e honestidade num governo pagão, sem deixar de orar três vezes por dia (Daniel 6.10). Dá pra ser fiel a Deus num lugar onde quase ninguém é.',
  },
  'Davi': {
    sub: 'Reino de Israel · por volta de 1000 a.C.',
    resumo: 'O pastor que virou o maior rei de Israel. Escreveu muitos salmos, caiu feio e voltou pra Deus de coração.',
    quem: 'O caçula dos filhos de Jessé, pastor de ovelhas, ungido rei ainda jovem. Enfrentou Golias, fugiu de Saul por anos e se tornou o maior rei de Israel. Escreveu boa parte dos Salmos. Deus prometeu que a família dele teria um trono pra sempre, promessa que se cumpre em Jesus, chamado Filho de Davi.',
    onde: '1 Samuel 16 a 1 Reis 2; 1 Crônicas 11-29; muitos Salmos.',
    deus: 'Quando Samuel vai ungir um dos filhos de Jessé, Deus avisa: o homem vê a aparência exterior, mas o Senhor examina os pensamentos e as intenções do coração (1 Samuel 16.7). Davi era o filho que ninguém tinha lembrado de chamar.\n\nNos salmos, Davi fala com Deus com muita honestidade, tanto na alegria quanto no pecado. O Salmo 51, escrito depois da queda com Bate-Seba, mostra o caminho de volta: confessar sem desculpas e confiar na misericórdia de Deus.',
    erros: 'Usou o poder de rei pra ter Bate-Seba, mulher de outro homem, e depois mandou matar o marido dela, Urias, pra esconder o que tinha feito. Também mandou contar o povo, algo que ele mesmo depois reconheceu como pecado, e isso trouxe castigo sobre o povo (2 Samuel 24).',
  },
  'Débora': {
    sub: 'Tempo dos juízes',
    resumo: 'Profetisa e juíza de Israel. Chamou Baraque pra batalha e cantou a vitória que veio de Deus.',
    quem: 'Profetisa e juíza de Israel. O povo ia até ela pra resolver suas questões. Débora convoca Baraque pra enfrentar o exército cananeu de Sísera e vai junto com ele. Depois da vitória, os dois cantam um cântico celebrando o que Deus fez.',
    onde: 'Juízes 4-5.',
    deus: 'No livro de Juízes, Israel vive um ciclo: se afasta de Deus, sofre, clama, e Deus levanta alguém pra libertar. Aqui Deus levanta Débora, uma mulher liderando o povo numa época em que isso era raro.\n\nA vitória é atribuída a Deus. Baraque hesita, e o chefe inimigo acaba derrotado pelas mãos de outra mulher, Jael. A força vem de Deus, e ele usa quem ele quer.',
  },
  'Elias': {
    sub: 'Reino dividido · séc. IX a.C.',
    resumo: 'O profeta do fogo no monte Carmelo, que logo depois quis desistir de tudo. Deus cuidou dele no deserto.',
    quem: 'Profeta que enfrentou o rei Acabe e a rainha Jezabel quando Israel estava tomado pela adoração a Baal. É lembrado pelo desafio no monte Carmelo, pela fuga pro deserto em profundo desânimo e por ter sido levado ao céu num redemoinho, sem passar pela morte.',
    onde: '1 Reis 17-19 e 21; 2 Reis 1-2.',
    deus: 'No Carmelo, Deus responde com fogo à oração de Elias e mostra, diante dos profetas de Baal, que ele é o único Deus verdadeiro.\n\nLogo depois, Elias foge com medo de Jezabel, deita debaixo de uma árvore e pede pra morrer. Deus manda comida, deixa ele dormir e só depois conversa. No monte Horebe, depois do vento, do terremoto e do fogo, vem um som de brisa suave (1 Reis 19.11-12). O mesmo Deus do fogo cuida com carinho de um profeta esgotado.\n\nSe você também está sem forças pra continuar, não fique sozinho com isso. Fale com alguém de confiança ou ligue 188, o CVV, a qualquer hora.',
    erros: 'Depois da grande vitória no Carmelo, entrou em desânimo e medo diante da ameaça de Jezabel e chegou a pedir a Deus que tirasse sua vida (1 Reis 19.4).',
  },
  'Eliseu': {
    sub: 'Reino dividido · séc. IX a.C.',
    resumo: 'Sucessor de Elias. Deus agiu por meio dele em milagres grandes e em necessidades bem do dia a dia.',
    quem: 'Discípulo e sucessor de Elias. Pediu uma porção dobrada do espírito dele e recebeu. Por meio de Eliseu, Deus fez muitos milagres em Israel, do azeite que não acabava na casa de uma viúva à cura de Naamã, um comandante sírio com lepra. Por décadas, aconselhou reis.',
    onde: '1 Reis 19; 2 Reis 2-13.',
    deus: 'Deus cura Naamã, um estrangeiro e comandante de um exército inimigo. A graça de Deus passa por cima de fronteiras, e Jesus lembra dessa história em Lucas 4.27.\n\nMilagres como o do azeite da viúva (2 Reis 4.1-7) mostram um Deus atento a problemas de casa, como uma dívida que ameaçava a família, e não só a grandes eventos da nação.',
  },
  'Enoque': {
    sub: 'Início da história',
    resumo: 'Andou com Deus, e Deus o levou. No meio de uma lista de gente que morreu, a história dele termina diferente.',
    quem: 'Descendente de Adão, pai de Matusalém e bisavô de Noé. A genealogia de Gênesis 5 repete o tempo todo a mesma frase: e morreu. Com Enoque é diferente. Ele sempre andou com Deus e um dia desapareceu, porque Deus o levou (Gênesis 5.24).',
    onde: 'Gênesis 5.21-24; citado em Hebreus 11.5 e Judas 14-15.',
    deus: 'Hebreus 11.5 diz que Enoque foi levado por causa da fé, e que antes disso recebeu o testemunho de que agradava a Deus. Numa lista marcada pela morte, Enoque aponta pra uma vida com Deus em que a morte não tem a última palavra.\n\nAndar com Deus é uma imagem de caminhada diária, passo a passo, lado a lado.',
  },
  'Esdras': {
    sub: 'Volta do exílio · séc. V a.C.',
    resumo: 'Sacerdote e estudioso da lei que ajudou o povo, de volta a Jerusalém, a reencontrar a Palavra de Deus.',
    quem: 'Sacerdote e escriba, um estudioso da lei de Moisés. Lidera um grupo de judeus de volta a Jerusalém com autorização do rei persa e se dedica a ensinar a lei ao povo. Trabalha junto com Neemias na reconstrução espiritual da comunidade.',
    onde: 'Esdras 7-10; Neemias 8.',
    deus: 'Deus usa até decretos de reis estrangeiros, como Ciro e Artaxerxes, pra trazer o povo de volta.\n\nQuando Esdras lê a lei em público, o povo chora e depois é chamado a celebrar (Neemias 8). Voltar pra terra não bastava, o povo precisava voltar pra Deus de coração. Esdras 7.10 resume a vida dele: decidiu estudar a lei do Senhor, praticá-la e ensiná-la.',
  },
  'Ester': {
    sub: 'Exílio · séc. V a.C.',
    resumo: 'Jovem judia que virou rainha da Pérsia e arriscou a vida pra salvar seu povo.',
    quem: 'Jovem judia criada pelo primo Mordecai, que se torna rainha do Império Persa. Quando um alto oficial, Hamã, arma um plano pra exterminar os judeus, Ester arrisca a vida entrando sem ser chamada na presença do rei pra pedir pelo seu povo. O nome de Deus não aparece nenhuma vez no livro.',
    onde: 'Livro de Ester.',
    deus: 'Mesmo sem o nome de Deus no texto, a mão dele aparece a história inteira: Ester chega ao palácio na hora certa, o rei perde o sono numa noite decisiva e tudo vira. Deus age até quando parece estar em silêncio.\n\nMordecai diz a Ester: quem sabe você chegou a essa posição justamente pra um momento como este? (Ester 4.14). Antes de agir, Ester pede que o povo jejue com ela.',
  },
  'Estêvão': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Servia os necessitados na igreja de Jerusalém e foi o primeiro cristão morto por causa da fé.',
    quem: 'Um dos sete escolhidos pela igreja de Jerusalém pra cuidar da distribuição de comida aos necessitados. A Bíblia o descreve como cheio de fé e do Espírito Santo. Depois de um discurso corajoso diante do conselho dos líderes judeus, é apedrejado. É o primeiro mártir cristão.',
    onde: 'Atos 6-7.',
    deus: 'Na hora da morte, Estêvão vê o céu aberto e Jesus em pé ao lado de Deus. Morre pedindo que Deus não leve em conta o pecado de quem o apedrejava, como Jesus fez na cruz. O evangelho sustentou Estêvão até o fim.\n\nNa cena está um jovem chamado Saulo, que aprovava a morte. Anos depois ele seria o apóstolo Paulo. A perseguição que começa ali espalha os cristãos e leva a mensagem pra além de Jerusalém (Atos 8.1-4).',
  },
  'Ezequias': {
    sub: 'Reino de Judá · por volta de 700 a.C.',
    resumo: 'Rei de Judá que confiou em Deus como poucos. Viu Jerusalém livre dos assírios, mas tropeçou na vaidade.',
    quem: 'Rei de Judá, filho de Acaz. Logo no começo do reinado desfaz a idolatria do pai: reabre e limpa o templo, volta a celebrar a Páscoa e derruba os altares de ídolos. Destrói até a serpente de bronze feita por Moisés, que o povo tinha transformado em objeto de culto (2 Reis 18.4). Quando o exército assírio cerca Jerusalém, Ezequias leva a carta de ameaça ao templo, abre diante de Deus e ora. A cidade é livrada sem batalha.',
    onde: '2 Reis 18-20; 2 Crônicas 29-32; Isaías 36-39.',
    deus: 'A Bíblia diz que nenhum rei de Judá confiou tanto no Senhor quanto Ezequias (2 Reis 18.5), e a libertação de Jerusalém aparece como resposta a essa confiança e à oração dele.\n\nDepois Ezequias fica doente, ora e recebe mais quinze anos de vida. Mesmo assim, mostra todos os tesouros do reino a mensageiros da Babilônia, por vaidade. Isaías avisa que tudo aquilo um dia seria levado pra lá, e assim aconteceu mais de cem anos depois. Uma vida de fé não deixa ninguém livre de tropeçar.',
    erros: 'Por orgulho, mostrou os tesouros do reino aos babilônios. Quando ouviu que o castigo viria depois da morte dele, pensou primeiro no próprio alívio: pelo menos haverá paz enquanto eu viver (2 Reis 20.19).',
  },
  'Ezequiel': {
    sub: 'Exílio · séc. VI a.C.',
    resumo: 'Sacerdote e profeta no exílio. Viu a glória de Deus sair do templo e ossos secos voltarem à vida.',
    quem: 'Sacerdote levado pra Babilônia junto com parte do povo de Judá. Lá recebe o chamado de profeta e visões fortes, como a da glória de Deus saindo do templo e a do vale de ossos secos. A mensagem dele junta alerta e esperança pra um povo longe de casa.',
    onde: 'Livro de Ezequiel.',
    deus: 'Na visão do capítulo 10, a glória de Deus deixa o templo de Jerusalém. A presença de Deus não fica presa a um prédio, e ela se retira diante da idolatria que o povo insistia em manter.\n\nNo capítulo 37, Deus mostra um vale cheio de ossos secos e pergunta se aqueles ossos podem viver. Pelo Espírito de Deus, eles voltam à vida. Deus consegue restaurar o que parece morto de vez.',
  },
  'Filipe apóstolo': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Um dos doze. Chamou Natanael com um convite simples, venha e veja, e pediu a Jesus pra ver o Pai.',
    quem: 'Discípulo de Betsaida, na Galileia, chamado diretamente por Jesus. Logo depois chama o amigo Natanael com um convite simples: venha e veja você mesmo (João 1.46). Faz parte dos doze e aparece em algumas conversas bem diretas com Jesus no evangelho de João.',
    onde: 'Mateus 10; Marcos 3; Lucas 6; João 1, 6, 12 e 14; Atos 1. Não confunda com Filipe, o evangelista de Atos 6 e 8.',
    deus: 'Diante da multidão com fome, Jesus pergunta a Filipe onde comprar pão, só pra testá-lo, porque já sabia o que ia fazer (João 6.5-6). Filipe faz as contas e diz que nem muito dinheiro daria. Aí vem a multiplicação. Deus age além do que os nossos cálculos alcançam.\n\nNa última ceia, Filipe pede: mostra o Pai pra nós. Jesus responde: quem me vê, vê o Pai (João 14.9). Uma pergunta sincera recebe uma das respostas mais claras sobre quem Jesus é.',
  },
  'Filipe evangelista': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Levou Jesus pra Samaria e, numa estrada deserta, explicou as Escrituras a um oficial da Etiópia.',
    quem: 'Um dos sete escolhidos pela igreja de Jerusalém pra servir os necessitados, junto com Estêvão. Com a perseguição, vai pra Samaria anunciar Jesus, e muita gente crê. Depois, orientado por um anjo, vai pra uma estrada deserta e encontra um oficial da Etiópia lendo Isaías. Explica o texto, fala de Jesus e o batiza ali mesmo.',
    onde: 'Atos 6, 8 e 21. Não confunda com Filipe, um dos doze apóstolos.',
    deus: 'Samaria era vista com desconfiança pelos judeus, e ali muita gente recebe Jesus. No meio desse movimento, Deus manda Filipe pra uma estrada vazia, sem explicar o motivo. Filipe vai, e o encontro leva o evangelho até a Etiópia.\n\nDeus prepara encontros específicos pra levar a boa notícia a todos os povos, como Jesus tinha anunciado em Atos 1.8.',
  },
  'Gideão': {
    sub: 'Tempo dos juízes',
    resumo: 'Um agricultor inseguro que Deus chamou pra libertar Israel com só trezentos homens.',
    quem: 'Agricultor da tribo de Manassés, com medo e sem confiança em si mesmo, chamado por Deus pra libertar Israel dos midianitas. Pede sinais mais de uma vez antes de acreditar no chamado. Depois lidera um exército reduzido a trezentos homens e vence uma multidão de inimigos.',
    onde: 'Juízes 6-8.',
    deus: 'Deus diminui de propósito o exército de Gideão pra que ninguém dissesse que venceu pela própria força (Juízes 7.2).\n\nDeus também tem paciência com a insegurança de Gideão e responde aos pedidos de confirmação. Quando o anjo aparece, chama Gideão de homem valente numa hora em que ele estava escondido, com medo (Juízes 6.12). Deus via nele o que ele ainda não via.',
    erros: 'Depois da vitória, fez com ouro um manto sacerdotal, que virou ídolo pra Israel e pra sua própria família. Teve muitas esposas, e um dos filhos, Abimeleque, trouxe violência ao povo depois da morte de Gideão.',
  },
};
