// Pessoas, de Isabel a Marta. Formato em reescrita-pessoas.mjs.
export const PESSOAS_B = {
  'Isabel': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Mãe de João Batista. Engravidou já idosa e foi a primeira a reconhecer que Maria carregava o Senhor.',
    quem: 'Parente de Maria, esposa do sacerdote Zacarias. A Bíblia diz que os dois eram justos diante de Deus. Isabel não conseguia ter filhos e já era idosa quando um anjo avisa Zacarias, no templo, que a oração deles tinha sido ouvida. Ela engravida de João Batista.',
    onde: 'Lucas 1.',
    deus: 'A gravidez de Isabel repete algo que aparece várias vezes na Bíblia: Deus dá filhos a mulheres que não podiam ter pra começar algo novo, como fez com Sara e com Ana.\n\nQuando Maria, grávida de Jesus, visita Isabel, o bebê pula na barriga dela e Isabel fica cheia do Espírito Santo. Ela chama Maria de mãe do meu Senhor (Lucas 1.43), reconhecendo quem era a criança antes de todo mundo.',
  },
  'Isaque': {
    sub: 'Patriarcas',
    resumo: 'O filho da promessa. Quase foi sacrificado no monte Moriá, e ali Deus providenciou um carneiro no lugar dele.',
    quem: 'Filho de Abraão e Sara, nascido quando os pais já eram bem idosos, depois de muitos anos de espera. A vida dele é mais discreta que a do pai e a do filho Jacó. É lembrado pela cena no monte Moriá, pelo casamento com Rebeca e por passar a promessa adiante pros filhos Esaú e Jacó.',
    onde: 'Gênesis 21-28 e 35.',
    deus: 'Deus cumpre a promessa quando, pela lógica humana, já não havia saída. No monte Moriá, Deus pede que Abraão ofereça Isaque e, na hora, providencia um carneiro no lugar dele. Abraão chama o lugar de o Senhor proverá (Gênesis 22.14). A cena aponta pra Jesus, o Cordeiro que Deus mesmo entregou.\n\nA escolha de Deus continua sendo graça: Jacó é escolhido antes de nascer, antes de ter feito qualquer coisa (Romanos 9.11).',
    erros: 'Repetiu o erro do pai e mentiu dizendo que Rebeca era sua irmã. Mais tarde, tinha um filho preferido, Esaú, e esse favoritismo abriu espaço pro engano de Jacó.',
  },
  'Isaías': {
    sub: 'Reino de Judá · séc. VIII a.C.',
    resumo: 'Profeta que viu a santidade de Deus no templo e anunciou o Servo que sofreria pelos pecados do povo.',
    quem: 'Profeta de Judá durante o reinado de vários reis. Foi chamado numa visão de Deus no templo, cercado de serafins que diziam santo, santo, santo (Isaías 6). O livro dele junta avisos contra a infidelidade do povo e algumas das promessas mais claras sobre o Messias em todo o Antigo Testamento.',
    onde: 'Livro de Isaías; contexto em 2 Reis 19-20.',
    deus: 'Diante da santidade de Deus, Isaías se sente perdido: sou um homem de lábios impuros. Um serafim toca a boca dele com uma brasa e diz que a culpa foi tirada (Isaías 6.5-7). Depois disso, quando Deus pergunta quem vai, Isaías responde: aqui estou, envia-me.\n\nEm Isaías 53, o profeta fala de um Servo ferido pelas nossas transgressões, que carrega o castigo que nos traz paz. Desde o começo, os cristãos leram esse texto como anúncio de Jesus (Atos 8.32-35).',
  },
  'Ismael': {
    sub: 'Patriarcas',
    resumo: 'Filho de Abraão com Agar. Mandado pro deserto com a mãe, ouviu de Deus que não estava esquecido.',
    quem: 'Filho de Abraão com Agar, a serva egípcia de Sara. Nasceu quando Abraão e Sara tentaram resolver do jeito deles a demora da promessa. O nome dele quer dizer Deus ouve. Anos depois, ele e a mãe são mandados embora pro deserto, e Deus ouve o choro do menino e mostra água pra eles.',
    onde: 'Gênesis 16, 17.18-20, 21.8-21 e 25.12-18; citado em Gálatas 4.21-31.',
    deus: 'A aliança seguiria por Isaque, e mesmo assim Deus não abandona Ismael. Promete fazer dele uma grande nação e salva a vida dele no deserto. Deus escolher uma família pra um propósito específico não significa que ele deixe de se importar com quem está fora dela.\n\nEm Gálatas 4, Paulo usa os dois filhos de Abraão como imagem: um nasceu do esforço humano, o outro da promessa. É a diferença entre tentar se salvar pela lei e receber a graça.',
  },
  'Jacó': {
    sub: 'Patriarcas',
    resumo: 'Enganou o irmão e o pai, fugiu, lutou com Deus e saiu dessa luta com um nome novo: Israel.',
    quem: 'Filho de Isaque e Rebeca, gêmeo de Esaú. O nome dele lembra a ideia de quem segura o calcanhar, ou de quem passa a perna nos outros. Depois de enganar o irmão e o pai pra ficar com a bênção, passa anos longe de casa, enganado pelo sogro Labão. Numa noite, luta com Deus e recebe um nome novo, Israel. Os doze filhos dele dão origem às tribos do povo.',
    onde: 'Gênesis 25-49.',
    deus: 'Deus escolhe e usa gente cheia de falhas, sem aprovar o que elas fazem de errado. Jacó estava longe de ser um exemplo, e mesmo assim a promessa passa por ele.\n\nEm Peniel, Jacó luta a noite inteira e sai mancando, abençoado e com outro nome (Gênesis 32). Deus trabalha no caráter de Jacó de perto, até a autossuficiência dar lugar à dependência.',
    erros: 'Aproveitou a fome do irmão pra ficar com o direito de primogênito e enganou o pai, já cego, pra roubar a bênção de Esaú. Depois, na própria família, repetiu o favoritismo e preferiu José aos outros filhos.',
  },
  'Jeremias': {
    sub: 'Reino de Judá · séc. VII e VI a.C.',
    resumo: 'Chamado ainda jovem, anunciou por décadas uma mensagem que ninguém queria ouvir, e também a promessa de uma nova aliança.',
    quem: 'Profeta de Judá nos últimos anos antes da queda de Jerusalém. Deus o chamou ainda jovem, e ele respondeu que era novo demais pra falar (Jeremias 1.6). Por décadas avisou sobre um castigo que o povo não queria ouvir. Foi preso, jogado num poço de lama e rejeitado. É conhecido como o profeta que chora.',
    onde: 'Livro de Jeremias; Lamentações é tradicionalmente atribuído a ele.',
    deus: 'Deus continua avisando o povo por meio de Jeremias mesmo sabendo que a mensagem seria rejeitada. É uma paciência que não força ninguém a responder.\n\nNo meio de tanto aviso, Jeremias 31 traz uma das promessas mais importantes do Antigo Testamento: uma nova aliança, com a lei de Deus escrita no coração. O objetivo final de Deus é restaurar. Jesus fala dessa nova aliança na última ceia (Lucas 22.20).',
    erros: 'No auge do sofrimento, reclamou com amargura do chamado e chegou a amaldiçoar o dia em que nasceu (Jeremias 20.14-18). A Bíblia registra essas orações sem cortar nada.',
  },
  'Jeroboão': {
    sub: 'Reino dividido · por volta de 930 a.C.',
    resumo: 'Primeiro rei do Norte de Israel. Recebeu uma promessa de Deus e trocou por dois bezerros de ouro.',
    quem: 'Servo de Salomão. O profeta Aías anuncia que dez tribos seriam tiradas do reino por causa da idolatria de Salomão e entregues a Jeroboão. Depois da morte de Salomão, ele se torna o primeiro rei do reino do Norte. Com medo de que o povo voltasse a ser fiel à família de Davi ao ir adorar em Jerusalém, faz dois bezerros de ouro em Betel e Dã e diz que aqueles eram os deuses que tiraram Israel do Egito.',
    onde: '1 Reis 11-14; 2 Crônicas 13.',
    deus: 'Deus oferece a Jeroboão uma promessa parecida com a que fez a Davi: se fosse fiel, a família dele também reinaria (1 Reis 11.38). Ele prefere a segurança política do momento.\n\nO resultado aparece por gerações. Durante dois séculos, os reis do Norte são descritos como quem andou nos pecados de Jeroboão. Uma decisão de conveniência religiosa de quem lidera pode marcar a vida de um povo inteiro.',
    erros: 'Espalhou a idolatria no reino com os bezerros de ouro, criou um sacerdócio próprio fora das regras dadas por Deus e ignorou o aviso direto de um profeta em Betel (1 Reis 13).',
  },
  'Jesus Cristo': {
    sub: 'Evangelhos · por volta de 4 a.C. a 30 d.C.',
    resumo: 'O Filho de Deus que se fez gente. A Bíblia inteira aponta pra ele.',
    quem: 'O Filho de Deus que se tornou humano, nascido de Maria em Belém. Viveu, ensinou e fez milagres na Galileia e na Judeia, morreu crucificado em Jerusalém e ressuscitou ao terceiro dia. Os quatro evangelhos o apresentam como o cumprimento das promessas do Antigo Testamento e o centro de toda a história da Bíblia.',
    onde: 'Mateus, Marcos, Lucas e João inteiros; em Atos, como o Senhor ressuscitado; em Apocalipse, como o Cordeiro que venceu.',
    tituloDeus: 'Por que ele é o centro',
    deus: 'As promessas do Antigo Testamento se encontram em Jesus: o descendente que esmagaria a serpente, o Servo sofredor de Isaías, o rei da família de Davi. A morte dele na cruz é apresentada como o sacrifício que resolve de vez o problema do pecado, e a ressurreição como a garantia de que a morte foi vencida.\n\nEle mesmo disse: eu sou o caminho, a verdade e a vida (João 14.6). O Novo Testamento inteiro foi escrito por gente convencida de que Jesus está vivo e é Senhor. Lida desse jeito, a Bíblia toda caminha em direção a ele. Pra conhecer mais, veja a lição [[01 - Trilha do Recém-Batizado/02 - Quem é Jesus|Quem é Jesus]].',
  },
  'Jezabel': {
    sub: 'Reino dividido · séc. IX a.C.',
    resumo: 'Rainha de Israel que perseguiu os profetas de Deus e armou a morte de um homem inocente por causa de uma vinha.',
    quem: 'Princesa fenícia, filha do rei de Sidom, casada com Acabe, rei de Israel. Traz o culto a Baal e a Aserá e sustenta centenas de profetas desses deuses com o dinheiro do palácio, enquanto persegue e manda matar os profetas do Senhor. Depois da derrota dos profetas de Baal no Carmelo, ameaça Elias de morte. Arma a morte de Nabote com acusação falsa pra Acabe ficar com a vinha dele. Morre anos depois do jeito que Elias tinha anunciado, jogada de uma janela em Jezreel.',
    onde: '1 Reis 16, 18-19 e 21; 2 Reis 9; citada em Apocalipse 2.20.',
    deus: 'No caso de Nabote, o crime tinha aparência de legalidade: testemunhas, julgamento, tudo arrumado. Deus viu o que estava por trás e mandou Elias ao lugar do crime pra anunciar o julgamento sobre Acabe e Jezabel (1 Reis 21.17-24). Poder nenhum protege do julgamento de Deus quem derrama sangue inocente.\n\nSéculos depois, o nome dela aparece em Apocalipse 2.20 como símbolo de uma falsa profetisa que desviava a igreja de Tiatira. O tipo de influência que ela representa continuou sendo uma ameaça.',
    erros: 'Perseguiu e matou profetas do Senhor, fez do culto a Baal uma política do reino e armou a morte de Nabote pra tomar a propriedade dele (1 Reis 21).',
  },
  'Jonas': {
    sub: 'Reino dividido · séc. VIII a.C.',
    resumo: 'O profeta que fugiu de Deus, foi engolido por um grande peixe e ficou bravo quando Deus perdoou os inimigos.',
    quem: 'Profeta de Israel no tempo do rei Jeroboão II (2 Reis 14.25). Deus manda Jonas pregar em Nínive, capital da Assíria, um império inimigo e violento. Ele foge na direção oposta. No meio de uma tempestade é jogado no mar, engolido por um grande peixe e devolvido à praia três dias depois. Quando finalmente prega em Nínive, a cidade inteira se arrepende. E Jonas fica com raiva.',
    onde: '2 Reis 14.25; livro de Jonas; citado por Jesus em Mateus 12.39-41.',
    deus: 'A parte mais desconfortável do livro está no final. Depois que Deus poupa Nínive, Jonas confessa por que fugiu: ele sabia que Deus é compassivo, misericordioso, paciente e cheio de amor (Jonas 4.2), e não queria isso pros inimigos.\n\nO livro termina com uma pergunta de Deus, sem resposta de Jonas. A pergunta fica pra quem lê: você consegue querer pros seus inimigos a mesma misericórdia que recebeu? Jesus usa a história de Jonas como sinal da própria morte e ressurreição.',
    erros: 'Fugiu da ordem de Deus, preferiu morrer a ver os ninivitas perdoados e ficou mais incomodado com uma planta que secou do que com a vida de mais de cento e vinte mil pessoas (Jonas 4.9-11).',
  },
  'Josias': {
    sub: 'Reino de Judá · por volta de 640 a 609 a.C.',
    resumo: 'Virou rei aos oito anos. Quando ouviu a lei de Deus lida, rasgou as roupas e fez a maior reforma da história de Judá.',
    quem: 'Rei de Judá que assume o trono aos oito anos, depois do pai e do avô que adoravam ídolos. Aos vinte e seis, numa reforma do templo, encontram um livro da lei que estava esquecido. Quando ouve a leitura, Josias rasga as próprias roupas ao perceber o quanto o povo tinha se afastado de Deus. Lidera então a reforma mais completa do Antigo Testamento: derruba os altares de ídolos e volta a celebrar a Páscoa como não se fazia havia séculos.',
    onde: '2 Reis 22-23; 2 Crônicas 34-35.',
    deus: 'A Bíblia diz que nenhum rei, antes ou depois, se voltou pro Senhor como Josias (2 Reis 23.25). Mesmo assim, o castigo anunciado por causa de gerações de idolatria só é adiado até depois da morte dele (2 Reis 22.19-20).\n\nDeus honra a fidelidade de um líder. Ela é preciosa, e mesmo assim não substitui o coração do povo inteiro voltando pra Deus.',
    erros: 'Morreu numa batalha contra o faraó Neco, mesmo avisado de que aquela guerra não era contra Judá. O texto diz que o aviso vinha de Deus, e Josias não ouviu (2 Crônicas 35.20-24).',
  },
  'Josué': {
    sub: 'Conquista de Canaã',
    resumo: 'Sucessor de Moisés. Levou o povo pra terra prometida e decidiu: eu e a minha casa serviremos ao Senhor.',
    quem: 'Ajudante de Moisés e um dos doze espiões enviados a Canaã. Junto com Calebe, foi o único que confiou que Deus daria a terra ao povo. Depois da morte de Moisés, lidera a travessia do rio Jordão, a entrada em Canaã e a divisão da terra entre as tribos.',
    onde: 'Números 13-14 e 27; livro de Josué.',
    deus: 'Deus cumpre a promessa feita a Abraão séculos antes. Na tomada de Jericó, os muros caem sem força militar, e fica claro que a vitória vem de Deus e da obediência a ele.\n\nAntes de começar, Deus diz a Josué pra ser forte e corajoso, porque estaria com ele por onde fosse (Josué 1.9). No fim da vida, Josué chama o povo a escolher a quem servir e dá o exemplo: eu e a minha casa serviremos ao Senhor (Josué 24.15).',
    erros: 'Josué e os líderes foram enganados pelos gibeonitas e fizeram um acordo de paz sem consultar a Deus antes (Josué 9.14).',
  },
  'José do Egito': {
    sub: 'Patriarcas',
    resumo: 'Vendido pelos irmãos como escravo, foi parar no Egito e virou governador. E perdoou quem o feriu.',
    quem: 'Filho preferido de Jacó. Por inveja, os irmãos o vendem como escravo, e ele vai parar no Egito. Lá passa anos de injustiça, inclusive preso por uma acusação falsa, até chegar a governar o país logo abaixo do faraó. A história dele fecha o livro de Gênesis e explica como a família de Jacó foi morar no Egito.',
    onde: 'Gênesis 37-50.',
    deus: 'No fim, José diz aos irmãos: vocês planejaram o mal contra mim, mas Deus tornou o mal em bem (Gênesis 50.20). O mal foi dos irmãos, e mesmo assim Deus usou até aquela injustiça pra salvar muita gente da fome.\n\nJosé escolhe perdoar quem o feriu, e perdoa chorando. A fidelidade dele em lugares que não escolheu, como a casa de Potifar e a prisão, fez parte do caminho.',
    erros: 'Quando jovem, contou aos irmãos, com ar de superioridade, os sonhos em que eles se curvavam diante dele. Isso aumentou o ódio que já sentiam, embora nada justifique o que fizeram com ele.',
  },
  'José pai adotivo de Jesus': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Carpinteiro de Nazaré que protegeu Maria e criou Jesus. A Bíblia não registra nenhuma fala dele, só atitudes.',
    quem: 'Carpinteiro de Nazaré, descendente de Davi, noivo de Maria. Descobre que ela está grávida antes do casamento e decide terminar o noivado em segredo, pra não expô-la. Um anjo aparece em sonho e explica que o bebê vinha do Espírito Santo. José obedece, casa com Maria e assume Jesus como filho.',
    onde: 'Mateus 1-2; Lucas 1-2.',
    deus: 'Antes mesmo de receber explicação, José já escolhe proteger Maria da vergonha pública. Depois obedece a cada instrução do anjo sem demora: casar, fugir pro Egito, voltar. Os evangelhos não registram nenhuma palavra dele.\n\nDeus usou a obediência silenciosa de um homem comum pra proteger Jesus quando ele era bebê.',
  },
  'João Batista': {
    sub: 'Evangelhos · séc. I',
    resumo: 'O profeta do deserto que preparou o caminho pra Jesus e disse: ele precisa crescer, e eu diminuir.',
    quem: 'Filho de Zacarias e Isabel, nascido quando os pais já eram idosos. Desde antes de nascer foi separado pra preparar o caminho do Messias. Pregava arrependimento no deserto, batizava no rio Jordão e apontou pra Jesus dizendo: vejam, o Cordeiro de Deus que tira o pecado do mundo (João 1.29). Foi preso e morto por Herodes.',
    onde: 'Mateus 3, 11 e 14; Marcos 1 e 6; Lucas 1, 3 e 7; João 1 e 3.',
    deus: 'Depois de séculos sem profetas, Deus envia João como o mensageiro anunciado por Isaías e Malaquias, pra preparar a chegada do Messias.\n\nQuando os discípulos de João reclamam que todo mundo estava indo atrás de Jesus, ele responde: ele deve tornar-se cada vez maior, e eu devo diminuir cada vez mais (João 3.30). Esse é o lugar de qualquer pessoa que serve a Deus: apontar pra Jesus.',
    erros: 'Na prisão, passou por um momento de dúvida e mandou perguntar a Jesus se ele era mesmo aquele que havia de vir (Mateus 11.3). Jesus respondeu mostrando o que estava acontecendo e depois elogiou João diante de todos.',
  },
  'João apóstolo': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Um dos três mais próximos de Jesus. Já quis mandar fogo do céu, e anos depois escreveu que Deus é amor.',
    quem: 'Filho de Zebedeu, pescador chamado junto com o irmão Tiago. Foi um dos três discípulos mais próximos de Jesus, presente na transfiguração e no Getsêmani. Jesus chamou os dois irmãos de filhos do trovão (Marcos 3.17). A tradição o reconhece como autor do quarto evangelho, de três cartas e do Apocalipse, escrito no exílio na ilha de Patmos.',
    onde: 'Os quatro evangelhos; Atos 3-4; 1, 2 e 3 João; Apocalipse.',
    deus: 'No evangelho, João se chama de o discípulo que Jesus amava. Ele viu de perto o carinho e a autoridade de Jesus, e o evangelho dele é o que mais insiste que Jesus é Deus.\n\nO rapaz que queria mandar fogo do céu sobre uma vila escreveu, anos depois, que Deus é amor (1 João 4.8). Já idoso e exilado, recebe as visões do Apocalipse, que mostram Deus no controle da história mesmo quando a igreja sofre.',
    erros: 'Junto com o irmão, pediu a Jesus os lugares de honra no reino, e os outros discípulos ficaram indignados. Numa outra vez, quis pedir fogo do céu contra uma vila samaritana que não recebeu Jesus, e Jesus o repreendeu (Lucas 9.54-55).',
  },
  'Judas Iscariotes': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Um dos doze. Andou com Jesus, cuidava do dinheiro do grupo e o entregou por trinta moedas de prata.',
    quem: 'Um dos doze apóstolos, responsável pela bolsa de dinheiro do grupo. Combina com os chefes dos sacerdotes entregar Jesus por trinta moedas de prata e o identifica aos soldados com um beijo, no Getsêmani. Depois da prisão de Jesus, sente remorso e morre. Mateus e Atos contam a morte dele com detalhes diferentes.',
    onde: 'Mateus 26-27; Marcos 14; Lucas 22; João 12-13 e 18; Atos 1.',
    deus: 'Os evangelhos não explicam tudo o que levou Judas a trair. João diz que ele já roubava do dinheiro do grupo (João 12.6) e que Satanás entrou nele naquela noite (João 13.27).\n\nJesus trata a traição como algo previsto nas Escrituras e, ao mesmo tempo, terrível: ai daquele por quem o Filho do homem é traído (Mateus 26.24). Deus estava no controle do que aconteceu na cruz, e Judas continuou responsável pelo que escolheu. A Bíblia segura essas duas verdades juntas.',
    erros: 'Traiu Jesus por dinheiro e o entregou com um beijo. Antes disso, já roubava da bolsa do grupo. O texto conta que ele sentiu remorso, e a história dele termina longe de Jesus. Pedro também falhou naquela noite, e voltou.',
  },
  'Judá filho de Jacó': {
    sub: 'Patriarcas',
    resumo: 'Sugeriu vender o irmão José e, anos depois, se ofereceu como escravo pra salvar outro irmão.',
    quem: 'Quarto filho de Jacó e Lia. É ele quem sugere vender José a mercadores em vez de matá-lo (Gênesis 37.26-27). Depois vive o episódio com a nora Tamar, que precisa enganá-lo pra receber o direito que ele tinha negado a ela (Gênesis 38). Anos mais tarde, diante de José já governador do Egito, Judá se oferece pra ficar como escravo no lugar do irmão mais novo, Benjamim, pra poupar o pai de mais uma dor.',
    onde: 'Gênesis 37-49; citado em Mateus 1.2-3 e Hebreus 7.14.',
    deus: 'A história de Judá mostra uma mudança real: de quem vende o irmão a quem se oferece no lugar do irmão. Deus trabalha no caráter das pessoas com o tempo.\n\nEm Gênesis 49.10, Jacó anuncia que o cetro não sairia de Judá. Da tribo dele vêm o rei Davi e Jesus, que Apocalipse 5.5 chama de Leão da tribo de Judá.',
    erros: 'Sugeriu vender José como escravo. Negou a Tamar o casamento com o filho mais novo, como mandava o costume, e depois dormiu com ela pensando que era uma prostituta. Quando descobriu tudo, reconheceu: ela é mais justa do que eu (Gênesis 38.26).',
  },
  'Jó': {
    sub: 'Livro de Jó · época dos patriarcas',
    resumo: 'Um homem íntegro que perdeu tudo, fez perguntas duras a Deus e ouviu a resposta dele.',
    quem: 'Homem íntegro e muito rico que perde os bens, os filhos e a saúde numa sequência de tragédias. O livro conta que isso acontece dentro de um desafio de Satanás, com a permissão de Deus. A maior parte do livro são conversas longas de Jó com amigos que tentam explicar o sofrimento dele, até que Deus mesmo fala.',
    onde: 'Livro de Jó.',
    deus: 'Deus não dá a Jó uma explicação do porquê. Em vez disso, mostra sua grandeza na criação (Jó 38-41). Confiar em Deus não depende de entender todos os porquês.\n\nO livro também desmonta a ideia de que todo sofrimento é castigo por algum pecado, que era o que os amigos de Jó diziam. No fim, Deus diz que os amigos não falaram o que era certo a respeito dele, e Jó sim (Jó 42.7). Jó levou a dor e as perguntas direto pra Deus, e isso contou mais do que as respostas prontas dos amigos.',
    erros: 'No meio da dor, questionou a justiça de Deus. Quando Deus fala, Jó reconhece que falou de coisas que não entendia e se arrepende (Jó 42.3-6).',
  },
  'Lia': {
    sub: 'Patriarcas',
    resumo: 'A esposa menos amada de Jacó. Deus viu o desprezo que ela sofria, e dela veio a família de Davi e de Jesus.',
    quem: 'Filha mais velha de Labão. Na noite do casamento, o pai a coloca no lugar da irmã Raquel, e Jacó só descobre de manhã. Lia passa a vida como a esposa menos amada. Mesmo assim, é mãe de seis dos doze filhos de Jacó, entre eles Levi e Judá.',
    onde: 'Gênesis 29-35 e 49.31.',
    deus: 'A Bíblia diz sem rodeios que Lia era desprezada e que por isso o Senhor lhe deu filhos (Gênesis 29.31). Deus toma o lado de quem é rejeitado dentro da própria família.\n\nOs nomes que ela dá aos filhos mostram a dor e a mudança. Primeiro espera que o marido passe a amá-la. No quarto filho, Judá, diz apenas: desta vez louvarei ao Senhor (Gênesis 29.35). Da família de Judá vêm Davi e Jesus.',
    erros: 'A Bíblia mostra Lia mais como vítima do arranjo do pai e da preferência do marido. Ela também entrou na rivalidade com a irmã pela atenção de Jacó (Gênesis 30.14-16).',
  },
  'Lucas evangelista': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Médico e companheiro de viagem de Paulo. Pesquisou com testemunhas antes de escrever o evangelho e o livro de Atos.',
    quem: 'Médico, provavelmente não judeu, companheiro de Paulo em parte das viagens missionárias. Em alguns trechos de Atos o texto passa a dizer nós, sinal de que o autor estava lá. A tradição reconhece Lucas como autor do terceiro evangelho e de Atos, os dois escritos pra um certo Teófilo.',
    onde: 'Citado em Colossenses 4.14, 2 Timóteo 4.11 e Filemom 24; autor tradicional de Lucas e Atos.',
    deus: 'Na abertura do evangelho, Lucas conta que investigou tudo com cuidado, a partir de testemunhas oculares, pra escrever em ordem (Lucas 1.1-4). A fé cristã se apoia em fatos que podem ser investigados.\n\nLucas presta atenção especial em mulheres, pobres e gente deixada de lado. É no evangelho dele que estão as histórias do filho pródigo, do bom samaritano e de Zaqueu. Quando Paulo estava preso e quase todos tinham ido embora, Lucas ficou com ele (2 Timóteo 4.11).',
  },
  'Lázaro': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Amigo de Jesus, morto havia quatro dias. Jesus chorou no túmulo e o chamou de volta à vida.',
    quem: 'Irmão de Marta e de Maria, morador de Betânia e amigo próximo de Jesus. Fica doente, as irmãs mandam avisar Jesus, e ele demora a chegar. Quando chega, Lázaro já estava sepultado havia quatro dias. Jesus manda tirar a pedra e chama Lázaro pra fora do túmulo, diante de muita gente.',
    onde: 'João 11-12.',
    deus: 'Diante do túmulo, Jesus chora (João 11.35), mesmo sabendo que ia ressuscitar o amigo em seguida. Ter poder sobre a morte não tira dele a compaixão por quem sofre com ela. Antes do milagre, Jesus diz a Marta: eu sou a ressurreição e a vida (João 11.25).\n\nO milagre também é um ponto de virada. Depois dele, os líderes religiosos decidem matar Jesus. O maior sinal de vida do evangelho de João leva direto ao caminho da cruz.',
  },
  'Lídia': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Empresária de tecidos em Filipos. Deus abriu o coração dela, e a casa dela virou o começo da igreja ali.',
    quem: 'Comerciante de tecidos de púrpura, um produto caro, natural de Tiatira e moradora de Filipos. Já buscava a Deus quando ouve Paulo falar num lugar de oração perto de um rio. Ela crê, é batizada com a família e insiste pra hospedar Paulo e seus companheiros. É a primeira pessoa na Europa que a Bíblia conta ter crido por meio de Paulo.',
    onde: 'Atos 16.13-15 e 16.40.',
    deus: 'Atos diz que o Senhor abriu o coração dela pra atender ao que Paulo dizia (Atos 16.14). A iniciativa é de Deus, e ela responde.\n\nA casa de Lídia vira o ponto de encontro da igreja em Filipos. Quando saem da prisão, Paulo e Silas vão pra lá encontrar os irmãos (Atos 16.40). Ela usou o que tinha, casa e recursos, pra servir.',
  },
  'Marcos evangelista': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Desistiu no meio de uma viagem missionária e anos depois ouviu de Paulo: ele me é útil. Uma história de segunda chance.',
    quem: 'Também chamado João Marcos, primo de Barnabé. A casa da mãe dele em Jerusalém era ponto de encontro da igreja. Acompanha Paulo e Barnabé na primeira viagem missionária, mas volta pra casa no meio do caminho. Mais tarde, Barnabé quer levá-lo de novo, Paulo não aceita, e os dois se separam por causa disso.',
    onde: 'Atos 12-13 e 15; citado em Colossenses 4.10, 2 Timóteo 4.11 e 1 Pedro 5.13. A tradição o reconhece como autor do evangelho de Marcos.',
    deus: 'No fim da vida, o mesmo Paulo que não quis levar Marcos pede que o tragam, porque ele é útil pro ministério (2 Timóteo 4.11). É um dos retratos mais completos de recomeço depois de um fracasso em toda a Bíblia.\n\nSegundo a tradição da igreja, o evangelho de Marcos registra o que Pedro contava. Isso ajuda a explicar o ritmo rápido do livro, cheio de ação.',
    erros: 'Abandonou Paulo e Barnabé no meio da primeira viagem missionária, em Perge (Atos 13.13), e isso fez Paulo desconfiar dele por um tempo.',
  },
  'Maria Madalena': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Libertada por Jesus, seguiu com ele até a cruz e foi a primeira a ver Jesus ressuscitado.',
    quem: 'Mulher de Magdala, na Galileia, libertada por Jesus de sete demônios. Passou a seguir Jesus e a ajudar a sustentar o grupo com os próprios recursos, junto com outras mulheres (Lucas 8.1-3). Esteve na crucificação e no sepultamento. Foi a primeira pessoa a ver Jesus ressuscitado e a levar a notícia aos discípulos.',
    onde: 'Mateus 27-28; Marcos 15-16; Lucas 8 e 24; João 19-20.',
    deus: 'Muita gente acha que Maria Madalena era a mulher pecadora que ungiu os pés de Jesus em Lucas 7, mas a Bíblia não diz isso. Lucas fala das duas em passagens diferentes, sem ligar uma à outra.\n\nNaquela época, o testemunho de uma mulher tinha pouco peso num tribunal. Mesmo assim, os quatro evangelhos contam que as primeiras testemunhas da ressurreição foram mulheres, e Maria Madalena está em todos eles. Quem fosse inventar a história dificilmente contaria desse jeito. No jardim, Jesus chama Maria pelo nome, e ela o reconhece (João 20.16).',
  },
  'Maria de Betânia': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Sentou aos pés de Jesus pra ouvir e, antes da cruz, derramou um perfume caríssimo nos pés dele.',
    quem: 'Irmã de Marta e de Lázaro, moradora de Betânia. É lembrada por sentar aos pés de Jesus pra ouvir enquanto a irmã cuidava do serviço da casa. Pouco antes da crucificação, derrama sobre os pés de Jesus um perfume de nardo puro, muito caro, e enxuga com os próprios cabelos.',
    onde: 'Lucas 10.38-42; João 11-12. Não confunda com Maria Madalena nem com Maria, mãe de Jesus.',
    deus: 'Quando criticam o perfume como desperdício, dizendo que o dinheiro podia ajudar os pobres, Jesus defende Maria. Diz que ela estava preparando o corpo dele pro sepultamento (João 12.7), e os outros evangelhos acrescentam que o gesto seria lembrado onde o evangelho fosse anunciado (Marcos 14.9).\n\nSentar aos pés de um mestre pra aprender era posição de discípulo, e na época isso era esperado de homens. Jesus diz que Maria descobriu a única coisa necessária, e que ninguém ia tirar isso dela (Lucas 10.42).',
  },
  'Maria': {
    sub: 'Evangelhos · séc. I',
    resumo: 'A jovem de Nazaré escolhida pra ser mãe de Jesus. Respondeu: aqui está a serva do Senhor.',
    quem: 'Jovem de Nazaré, noiva de José. O anjo Gabriel anuncia que ela seria mãe do Filho de Deus pelo Espírito Santo, e Maria responde: eu sou a serva do Senhor; que aconteça tudo o que o Senhor me disse (Lucas 1.38). Acompanhou o ministério de Jesus, esteve ao pé da cruz e estava entre os discípulos reunidos em oração depois da ascensão.',
    onde: 'Mateus 1-2; Lucas 1-2 e 8; João 2 e 19; Atos 1.14.',
    deus: 'Deus escolhe uma jovem comum, sem riqueza nem posição, pro papel mais único da história da salvação. No cântico de Lucas 1.46-55, Maria celebra um Deus que derruba os poderosos dos seus tronos e levanta os humildes.\n\nAo pé da cruz, Maria vê o filho sofrer. E Jesus, no meio da dor, cuida dela e a entrega aos cuidados do discípulo João (João 19.26-27).',
    erros: 'Num momento, a família de Jesus, com Maria junto, foi atrás dele sem entender a missão que ele cumpria. Jesus aproveitou pra dizer que a família dele é quem faz a vontade de Deus (Marcos 3.21 e 3.31-35).',
  },
  'Marta': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Recebeu Jesus em casa, se enrolou no serviço e fez uma das declarações de fé mais completas do evangelho.',
    quem: 'Irmã de Maria e de Lázaro, moradora de Betânia. Recebe Jesus em casa e fica ocupada com os preparativos enquanto a irmã senta pra ouvi-lo. Quando Lázaro morre, é Marta quem sai ao encontro de Jesus e conversa com ele sobre a ressurreição.',
    onde: 'Lucas 10.38-42; João 11-12.',
    deus: 'Quando Marta reclama da irmã, Jesus responde com carinho: Marta, Marta, você está tão preocupada com todos esses serviços; há apenas uma coisa necessária (Lucas 10.41-42). Jesus valoriza o serviço dela e coloca em ordem o que vem primeiro.\n\nDiante da morte do irmão, Marta diz: eu creio que tu és o Cristo, o Filho de Deus, que devia vir ao mundo (João 11.27). Ela faz essa declaração antes de ver o milagre.',
    erros: 'Reclamou com Jesus porque estava sobrecarregada enquanto a irmã só ouvia, e cobrou dele que mandasse Maria ajudar.',
  },
};
