// Pessoas, de Mateus a Zaqueu. Formato em reescrita-pessoas.mjs.
export const PESSOAS_C = {
  'Mateus apóstolo': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Cobrador de impostos, malvisto pelo próprio povo. Jesus o chamou direto da mesa de trabalho.',
    quem: 'Cobrador de impostos, também chamado Levi, que trabalhava pro domínio romano. Jesus passa pela mesa dele e diz: siga-me. Mateus levanta e vai. Depois oferece um jantar em casa com outros cobradores de impostos e gente considerada pecadora, e os fariseus criticam Jesus por estar ali.',
    onde: 'Mateus 9-10; Marcos 2-3; Lucas 5-6; Atos 1.',
    deus: 'Os cobradores de impostos eram vistos como traidores que exploravam o próprio povo. Chamando justamente um deles, Jesus deixa claro pra quem veio: quem precisa de médico são os doentes, e não os que têm saúde (Mateus 9.12).\n\nA tradição atribui a Mateus o primeiro evangelho, que mostra com muito cuidado como Jesus cumpre as promessas do Antigo Testamento.',
    erros: 'Antes do chamado, cobrava impostos pra Roma, uma função conhecida por exploração e desonestidade.',
  },
  'Melquisedeque': {
    sub: 'Patriarcas',
    resumo: 'Rei e sacerdote misterioso que abençoou Abraão. Hebreus usa a figura dele pra explicar o sacerdócio de Jesus.',
    quem: 'Rei de Salém e sacerdote do Deus Altíssimo. Aparece de repente em Gênesis 14, sem nenhuma informação sobre família, abençoa Abraão depois de uma batalha e recebe dele a décima parte de tudo. Some da história do mesmo jeito que apareceu, e volta a ser citado no Salmo 110.4, ligado ao rei que Deus prometeu.',
    onde: 'Gênesis 14.18-20; Salmo 110.4; Hebreus 5-7.',
    deus: 'Hebreus 7 usa o fato de a Bíblia não registrar a família nem a morte de Melquisedeque como imagem de Jesus. O sacerdócio de Jesus não depende de descendência e não tem fim: ele é sacerdote pra sempre, segundo a ordem de Melquisedeque.\n\nA cena também mostra Abraão reconhecendo um sacerdote do Deus Altíssimo fora da própria família. Deus já tinha gente sua entre outros povos antes de formar Israel.',
  },
  'Miriã': {
    sub: 'Êxodo e deserto',
    resumo: 'Irmã de Moisés. Ainda menina ajudou a salvar o irmão no rio Nilo e, adulta, liderou o louvor depois do mar Vermelho.',
    quem: 'Irmã de Moisés e de Arão. Ainda menina, vigia o cesto do irmão bebê no rio Nilo e, quando a filha do faraó o encontra, sugere chamar uma mulher hebreia pra amamentá-lo: a própria mãe deles (Êxodo 2.4-8). Adulta e reconhecida como profetisa, pega um tamborim e lidera as mulheres num canto de vitória depois da travessia do mar Vermelho (Êxodo 15.20-21).',
    onde: 'Êxodo 2 e 15.20-21; Números 12 e 20.1.',
    deus: 'Deus usa Miriã pra salvar o irmão e pra liderar a adoração do povo. A mesma Miriã, mais tarde, se junta a Arão pra questionar a autoridade de Moisés e é atingida por uma doença de pele (Números 12).\n\nQuem já foi muito usado por Deus também precisa ser corrigido quando se levanta contra o que ele estabeleceu. E Moisés, o irmão criticado, ora pela cura dela. Deus corrige sem abandonar: depois de sete dias, Miriã volta ao acampamento.',
    erros: 'Com Arão, criticou Moisés por causa da esposa cuxita e questionou se Deus falava só por meio dele (Números 12.1-2).',
  },
  'Moisés': {
    sub: 'Êxodo e deserto',
    resumo: 'Salvo das águas quando bebê, criado no palácio, fugitivo no deserto. Deus o chamou numa sarça em chamas pra libertar seu povo.',
    quem: 'Nasceu hebreu no Egito, num tempo em que o faraó mandava matar os meninos hebreus. Foi salvo num cesto no rio, criado no palácio do faraó e depois fugiu pro deserto. Lá, Deus o chama numa sarça que pegava fogo sem se queimar e o envia pra libertar Israel. Moisés lidera o povo na saída do Egito, recebe a lei no monte Sinai e guia o povo por quarenta anos no deserto.',
    onde: 'Êxodo 2-40, Levítico, Números e Deuteronômio; citado em todo o Antigo e o Novo Testamento.',
    deus: 'Deus ouve o clamor de um povo escravizado e age pra libertar. É nesse contexto que revela o próprio nome: Eu Sou o que Sou (Êxodo 3.14).\n\nNo Sinai, a ordem importa. Primeiro Deus liberta o povo, depois dá os mandamentos. Os dez mandamentos começam lembrando: eu sou o Senhor, o seu Deus, que tirou você do Egito (Êxodo 20.2). A obediência vem como resposta a uma salvação que o povo já recebeu.',
    erros: 'Matou um egípcio e fugiu. Resistiu ao chamado de Deus com várias desculpas, inclusive a de que não sabia falar bem. Mais tarde, em vez de falar com a rocha como Deus mandou, bateu nela com raiva, e por isso não entrou na terra prometida (Números 20.10-12).',
  },
  'Natã': {
    sub: 'Reino de Israel · por volta de 1000 a.C.',
    resumo: 'O profeta que levou a Davi a maior promessa e, anos depois, a acusação mais dura: você é o homem rico da história.',
    quem: 'Profeta na corte do rei Davi. Leva a Davi a promessa de que a família dele reinaria pra sempre (2 Samuel 7). Anos depois, volta com uma história sobre um homem rico que rouba a única ovelhinha de um pobre. Davi fica indignado e condena o homem, e Natã responde: você é o homem rico da história. Era a história do pecado de Davi com Bate-Seba e Urias. Mais tarde, Natã ajuda a garantir que Salomão seja o rei.',
    onde: '2 Samuel 7 e 12; 1 Reis 1; 1 Crônicas 17.',
    deus: 'Natã levou a Davi tanto a promessa quanto a acusação, sem suavizar nenhuma das duas. Ser próximo de Deus não livrou Davi de ser confrontado quando pecou.\n\nNatã usou uma história pra Davi enxergar o próprio pecado. Davi se arrependeu, e o Salmo 51 mostra esse arrependimento. A correção de Deus busca trazer a pessoa de volta.',
  },
  'Neemias': {
    sub: 'Volta do exílio · séc. V a.C.',
    resumo: 'Copeiro do rei da Pérsia que deixou a posição pra reconstruir os muros de Jerusalém, orando em cada passo.',
    quem: 'Copeiro do rei persa Artaxerxes, um cargo de muita confiança. Quando fica sabendo que os muros de Jerusalém estavam em ruínas, chora, jejua, ora e pede ao rei permissão pra ir reconstruir. Enfrenta oposição o tempo todo, organiza o povo pro trabalho e também lidera uma renovação espiritual.',
    onde: 'Livro de Neemias.',
    deus: 'Deus abre caminho por meio de um funcionário de confiança num império pagão. Neemias não tinha cargo religioso, e Deus usou o lugar onde ele estava.\n\nNeemias ora antes de agir o tempo inteiro, inclusive com orações bem rápidas no meio de uma conversa com o rei (Neemias 2.4). Orar e trabalhar andam juntos na vida dele.',
    erros: 'O livro mostra Neemias como alguém íntegro, mas em alguns confrontos ele age com muita dureza contra quem desobedecia (Neemias 13.25).',
  },
  'Nicodemos': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Um líder religioso que foi falar com Jesus de noite. Ouviu sobre nascer de novo e, aos poucos, tomou coragem.',
    quem: 'Fariseu e membro do conselho dos líderes judeus. Procura Jesus de noite pra conversar, e Jesus fala sobre nascer de novo, o que Nicodemos não entende de primeira. Mais tarde defende, sozinho, que Jesus tivesse um julgamento justo. Depois da crucificação, ajuda a preparar o corpo de Jesus pro sepultamento, com uma grande quantidade de perfumes.',
    onde: 'João 3, 7.50-52 e 19.39.',
    deus: 'Foi pra Nicodemos, um líder religioso respeitado, que Jesus disse: Deus amou tanto o mundo que deu o seu Filho único para que todo aquele que crer nele não pereça, mas tenha a vida eterna (João 3.16). Ser religioso e conhecer a lei não bastava. Nicodemos precisava nascer de novo, como qualquer pessoa.\n\nA história dele vai da visita de noite ao gesto público de cuidar do corpo de Jesus. A fé dele cresceu devagar, e cresceu.',
    erros: 'Mesmo sendo mestre em Israel, não entendeu de primeira o que Jesus dizia sobre nascer de novo, e Jesus estranhou isso (João 3.9-10).',
  },
  'Noé': {
    sub: 'Início da história',
    resumo: 'Construiu a arca quando todo mundo tinha se corrompido. Depois do dilúvio, Deus fez com ele a aliança do arco-íris.',
    quem: 'Gênesis descreve Noé como um homem justo e íntegro no meio de uma geração corrompida, alguém que vivia de acordo com a vontade de Deus. Deus manda Noé construir uma arca pra salvar a família e os animais do dilúvio. Depois que as águas baixam, Noé recomeça a vida na terra e recebe uma aliança de Deus.',
    onde: 'Gênesis 6-9; citado em Hebreus 11.7 e 2 Pedro 2.5.',
    deus: 'Deus leva o mal a sério e julga, e antes do julgamento abre um caminho de salvação. Pedro lembra que Noé era o único homem que falava a favor de Deus (2 Pedro 2.5).\n\nDepois do dilúvio, Deus reconhece que o coração humano continua inclinado pro mal (Gênesis 8.21) e mesmo assim promete sustentar a terra. O arco-íris é o sinal desse compromisso.',
    erros: 'Depois do dilúvio, se embriagou e ficou nu dentro da tenda. O episódio termina com uma maldição sobre Canaã, um dos netos dele (Gênesis 9.20-27). Esse texto foi usado por muito tempo, de forma errada, pra justificar a escravidão de pessoas negras. A Bíblia não diz nada disso.',
  },
  'Paulo': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Perseguia cristãos até encontrar Jesus na estrada de Damasco. Virou o maior missionário do Novo Testamento.',
    quem: 'Fariseu chamado Saulo, que perseguia a igreja com força. A caminho de Damasco, encontra Jesus ressuscitado numa luz do céu, e a vida dele muda completamente. Torna-se o grande missionário entre os povos não judeus, começa igrejas pela Ásia Menor e pela Grécia e escreve boa parte das cartas do Novo Testamento.',
    onde: 'Atos 9-28; as cartas de Romanos a Filemom.',
    deus: 'A conversão de Paulo é um dos maiores exemplos da graça de Deus alcançando quem parecia não ter chance: o perseguidor da igreja vira o maior anunciador de Jesus. Ele mesmo se chamou o pior dos pecadores e disse que Deus mostrou nele toda a sua paciência (1 Timóteo 1.15-16).\n\nNas cartas, principalmente em Romanos e Gálatas, Paulo explica que ninguém é declarado justo diante de Deus por cumprir a lei. A pessoa é declarada justa pela fé em Cristo.',
    erros: 'Antes da conversão, perseguiu cristãos e aprovou a morte de Estêvão. Já como apóstolo, teve uma discussão forte com Barnabé por causa de Marcos, e os dois se separaram (Atos 15.36-40).',
  },
  'Pedro': {
    sub: 'Evangelhos e igreja primitiva · séc. I',
    resumo: 'O pescador impulsivo que negou Jesus três vezes, foi restaurado e pregou no dia de Pentecostes.',
    quem: 'Pescador da Galileia chamado Simão, um dos primeiros discípulos de Jesus e o que mais aparece entre os doze. Jesus deu a ele o nome Pedro, que quer dizer pedra. Na noite da prisão de Jesus, nega três vezes que o conhece. Depois da ressurreição é restaurado e se torna um dos principais líderes da igreja em Jerusalém.',
    onde: 'Os quatro evangelhos; Atos 1-12 e 15; 1 e 2 Pedro.',
    deus: 'À beira do mar da Galileia, Jesus pergunta três vezes a Pedro: você me ama? (João 21). Três perguntas pra três negações. A cada resposta, Jesus devolve a missão: cuide das minhas ovelhas. Jesus restaura quem falhou e confia a ele de novo o trabalho.\n\nEm Atos, é Pedro quem prega no Pentecostes, quando cerca de três mil pessoas creem, e quem entra na casa de Cornélio, abrindo a porta do evangelho aos não judeus.',
    erros: 'Negou Jesus três vezes, poucas horas depois de jurar que morreria com ele. Anos mais tarde, em Antioquia, deixou de comer com os cristãos não judeus pra agradar um grupo de Jerusalém, e Paulo o confrontou em público (Gálatas 2.11-14).',
  },
  'Priscila e Áquila': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Casal que fazia tendas, hospedou Paulo e ensinou Apolo com respeito e em particular.',
    quem: 'Casal de fabricantes de tendas expulso de Roma, junto com outros judeus, por ordem do imperador Cláudio. Vão morar em Corinto, onde recebem Paulo e trabalham com ele no mesmo ofício. Depois vão pra Éfeso. Quando ouvem Apolo pregar com conhecimento incompleto, chamam o pregador em particular e explicam com mais clareza o caminho de Deus (Atos 18.26).',
    onde: 'Atos 18; Romanos 16.3-4; 1 Coríntios 16.19; 2 Timóteo 4.19.',
    deus: 'Na maioria das vezes em que o casal aparece, o nome de Priscila vem antes do de Áquila, algo pouco comum na época. Isso pode indicar que ela tinha papel de destaque no ensino e no serviço dos dois.\n\nO jeito como corrigem Apolo ensina muito: em particular, com respeito, sem expor. Em Romanos 16, Paulo diz que eles arriscaram a vida por ele e que a igreja se reunia na casa deles. Um casal comum, com trabalho comum, servindo a Deus com o que tinha.',
  },
  'Raabe': {
    sub: 'Conquista de Canaã',
    resumo: 'Uma prostituta de Jericó que escondeu os espiões de Israel, confiou no Deus deles e entrou na família de Jesus.',
    quem: 'Mulher cananeia de Jericó, conhecida como prostituta. Esconde os dois espiões enviados por Josué e engana os soldados do rei sobre onde eles estavam. Em troca, pede que ela e a família sejam poupadas quando a cidade cair. Quando os muros de Jericó desabam, Raabe e os seus são salvos.',
    onde: 'Josué 2 e 6.22-25; citada em Mateus 1.5, Hebreus 11.31 e Tiago 2.25.',
    deus: 'Raabe diz aos espiões que já tinha ouvido o que Deus fez por Israel e reconhece: o Senhor, o Deus de vocês, é o supremo Deus do céu e da terra (Josué 2.11). Hebreus 11.31 destaca a fé dela, e Tiago 2.25 destaca a atitude que mostrou essa fé. Os dois textos olham pra mesma história por lados diferentes.\n\nMateus 1.5 coloca Raabe na genealogia de Jesus. A família do Messias inclui uma estrangeira com um passado que muita gente preferiria esconder.',
    erros: 'Mentiu aos soldados do rei pra proteger os espiões (Josué 2.4-5). O texto não apresenta essa mentira como exemplo e se concentra na fé que a levou a escolher o lado de Deus.',
  },
  'Raquel': {
    sub: 'Patriarcas',
    resumo: 'A esposa amada de Jacó. Esperou anos por um filho, viveu em rivalidade com a irmã e foi mãe de José e Benjamim.',
    quem: 'Filha mais nova de Labão e esposa amada de Jacó, que trabalhou catorze anos pra casar com ela depois de ser enganado e casado primeiro com Lia. Por anos, Raquel não consegue ter filhos enquanto a irmã tem vários. Até que Deus se lembra dela e ela dá à luz José. Morre mais tarde no parto de Benjamim, perto de Belém.',
    onde: 'Gênesis 29-35; citada em Jeremias 31.15 e Mateus 2.18.',
    deus: 'O texto diz que Deus se lembrou de Raquel, ouviu e deu a ela um filho (Gênesis 30.22), depois de anos de espera e de rivalidade dolorosa com a irmã.\n\nSéculos depois, Jeremias usa a imagem de Raquel chorando pelos filhos pra falar da dor do exílio, e Mateus retoma a mesma imagem pra falar das crianças mortas por Herodes em Belém. A dor de uma mãe vira símbolo da dor de um povo, e Deus não fica indiferente a ela.',
    erros: 'Roubou os ídolos da casa do pai quando fugiu com Jacó e mentiu pra escondê-los (Gênesis 31.19 e 31.34-35). E viveu uma rivalidade amarga com a irmã por causa dos filhos.',
  },
  'Rebeca': {
    sub: 'Patriarcas',
    resumo: 'Generosa com um estranho no poço, virou esposa de Isaque. Anos depois, armou o engano pra Jacó ficar com a bênção.',
    quem: 'O servo de Abraão vai procurar uma esposa pra Isaque e ora pedindo um sinal. Rebeca aparece no poço e oferece água não só a ele, mas também aos camelos, e é reconhecida como a escolhida. Grávida de gêmeos que já brigavam na barriga, ouve de Deus que o mais velho serviria ao mais novo. Mais tarde, arma o plano pra Jacó, o filho preferido dela, receber a bênção que Isaque queria dar a Esaú.',
    onde: 'Gênesis 24-27.',
    deus: 'Paulo usa a escolha de Jacó, anunciada a Rebeca antes de os meninos nascerem, pra mostrar que a escolha de Deus vem da graça dele, antes de qualquer obra (Romanos 9.10-13).\n\nA história também mostra como essa escolha se cumpriu no meio de um engano. Deus realiza seus planos por meio de pessoas reais e falhas, sem aprovar o que elas fazem de errado.',
    erros: 'Armou o engano de Isaque, já velho e cego, pra que Jacó recebesse a bênção de Esaú, usando disfarce e mentira (Gênesis 27).',
  },
  'Rute': {
    sub: 'Tempo dos juízes',
    resumo: 'Uma estrangeira que ficou ao lado da sogra quando podia ir embora: o seu povo será o meu povo, e o seu Deus, o meu Deus.',
    quem: 'Mulher de Moabe, um povo vizinho de Israel. Fica viúva e, em vez de voltar pra sua família, escolhe ficar com a sogra, Noemi, que também tinha perdido tudo. Diz a ela: o seu povo será o meu povo, e o seu Deus será o meu Deus (Rute 1.16). Em Belém, trabalha colhendo nos campos de Boaz, casa com ele e se torna bisavó do rei Davi.',
    onde: 'Livro de Rute; citada em Mateus 1.5.',
    deus: 'O livro de Rute acontece num tempo de muita confusão moral, e mesmo assim não tem nenhum milagre espetacular. Deus age por meio da lealdade de Rute, da bondade de Boaz e de leis que protegiam os pobres e as viúvas.\n\nUma estrangeira de Moabe entra na família de Davi e, depois, na genealogia de Jesus. A graça de Deus sempre foi maior que as fronteiras de Israel.',
  },
  'Salomão': {
    sub: 'Reino de Israel · por volta de 970 a 930 a.C.',
    resumo: 'Filho de Davi, pediu sabedoria a Deus e construiu o templo. No fim da vida, deixou o coração se desviar.',
    quem: 'Filho de Davi e Bate-Seba e terceiro rei de Israel. É conhecido pela sabedoria que recebeu de Deus, pela construção do templo em Jerusalém e por um reinado de paz e riqueza. A tradição liga o nome dele a Provérbios, Eclesiastes e Cântico dos Cânticos.',
    onde: '1 Reis 1-11; 2 Crônicas 1-9.',
    deus: 'Quando Deus diz a Salomão que peça o que quiser, ele pede sabedoria pra governar bem, em vez de riqueza ou vida longa. Deus dá a sabedoria e acrescenta o resto (1 Reis 3.5-14).\n\nO templo que Salomão constrói cumpre a promessa feita a Davi. Só que o próprio Salomão, no fim da vida, se afasta de Deus. Nem sabedoria nem privilégio protegem automaticamente alguém de cair.',
    erros: 'Casou com muitas mulheres de povos que adoravam outros deuses e, na velhice, deixou o coração se desviar atrás desses deuses, chegando a construir altares pra eles (1 Reis 11.1-8). Isso preparou a divisão do reino depois da sua morte.',
  },
  'Samuel': {
    sub: 'Tempo dos juízes · por volta de 1050 a.C.',
    resumo: 'Ouviu Deus chamar seu nome ainda menino, no santuário. Foi o último juiz de Israel e ungiu os dois primeiros reis.',
    quem: 'Filho de Ana, entregue ainda pequeno pra servir no santuário de Siló. Numa noite, ouve alguém chamar seu nome e pensa que é o sacerdote Eli. Era Deus. Samuel responde: fale, o seu servo está ouvindo (1 Samuel 3.10). Cresce como o último juiz de Israel e um grande profeta, e unge Saul e depois Davi como reis.',
    onde: '1 Samuel 1-25.',
    deus: 'Deus responde à oração de uma mulher que não conseguia ter filhos e, por meio desse filho, volta a falar com o povo numa época em que as mensagens do Senhor eram muito raras (1 Samuel 3.1).\n\nQuando o povo pede um rei pra ser como as outras nações, Deus atende, mesmo sabendo dos problemas que isso traria. Deus tem paciência com a insistência humana e continua levando adiante seus planos.',
    erros: 'Colocou os próprios filhos como juízes, e eles eram desonestos e aceitavam suborno. Esse foi um dos motivos que o povo usou pra pedir um rei (1 Samuel 8.1-5).',
  },
  'Sansão': {
    sub: 'Tempo dos juízes',
    resumo: 'Tinha uma força enorme e decisões péssimas. Mesmo cego e preso, pediu força a Deus uma última vez.',
    quem: 'Juiz de Israel separado pra Deus desde antes de nascer, com o voto de nazireu, que incluía não cortar o cabelo. Tinha uma força fora do comum e vivia em conflito com os filisteus, que dominavam Israel. A vida dele é marcada por decisões impulsivas, principalmente com mulheres filisteias. Dalila descobre o segredo da força, e ele perde a força, a visão e a liberdade.',
    onde: 'Juízes 13-16; citado em Hebreus 11.32.',
    deus: 'Depois de Sansão ser cegado e humilhado, o texto diz que o cabelo dele começou a crescer de novo (Juízes 16.22). Preso num templo pagão, ele ora pedindo força mais uma vez e derruba o prédio sobre os filisteus e sobre si mesmo.\n\nDeus usa Sansão até o fim, apesar de uma vida inteira de impulsos, e isso mostra a paciência de Deus. Também mostra que ter um dom de Deus não garante um caráter à altura dele. Dom e maturidade são coisas diferentes.',
    erros: 'Quebrou várias vezes o voto que tinha, contou o segredo da força a Dalila mesmo depois de ela tentar entregá-lo três vezes, e usou a própria força muitas vezes pra vingança pessoal.',
  },
  'Sara': {
    sub: 'Patriarcas',
    resumo: 'Esposa de Abraão. Riu quando ouviu que teria um filho na velhice, e o filho nasceu. O nome dele, Isaque, quer dizer riso.',
    quem: 'Esposa de Abraão, que deixou Ur com ele rumo a uma terra desconhecida. Não conseguiu ter filhos por décadas. Já idosa, ouve escondida a promessa de que teria um filho e ri por dentro, sem acreditar. Depois nega que riu. Mesmo assim, dá à luz Isaque, cujo nome quer dizer riso.',
    onde: 'Gênesis 11-23; citada em Hebreus 11.11 e 1 Pedro 3.6.',
    deus: 'Diante do riso de Sara, Deus pergunta a Abraão: existe alguma coisa difícil demais pro Senhor? (Gênesis 18.14). E cumpre a promessa. Quando Isaque nasce, Sara diz que Deus a fez rir, e que todos iam rir com ela (Gênesis 21.6). O riso de dúvida vira riso de alegria.\n\nHebreus 11.11 fala da fé de Sara, e não só da de Abraão. Ela também faz parte da história da promessa.',
    erros: 'Deu a serva Hagar a Abraão pra ter um filho por meio dela. Quando Hagar engravidou, Sara passou a maltratá-la e, anos depois, pediu a Abraão que mandasse Hagar e Ismael embora (Gênesis 16 e 21).',
  },
  'Saul': {
    sub: 'Reino de Israel · por volta de 1050 a 1010 a.C.',
    resumo: 'O primeiro rei de Israel. Começou humilde e foi se perdendo entre desobediência, ciúme e medo.',
    quem: 'Primeiro rei de Israel, escolhido quando o povo pediu um rei como as outras nações tinham. Alto e bonito, começa com humildade, a ponto de se esconder no meio da bagagem no dia em que seria apresentado (1 Samuel 10.22). Com o tempo, desobedece a Deus, fica tomado pelo ciúme de Davi e passa anos tentando matá-lo.',
    onde: '1 Samuel 9-31.',
    deus: 'Deus deixa o povo ter o rei que pediu, mesmo sabendo das dificuldades. E a rejeição de Saul vem depois de desobediências concretas.\n\nQuando Saul tenta se justificar dizendo que guardou animais pra oferecer a Deus, Samuel responde: obedecer é melhor do que sacrificar (1 Samuel 15.22). Deus quer obediência sincera, mais do que aparência de religião.',
    erros: 'Ofereceu um sacrifício que não cabia a ele, desobedeceu à ordem de Deus na guerra contra os amalequitas, perseguiu Davi por anos por ciúme e, no fim, foi consultar uma médium em En-Dor.',
  },
  'Silas': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Parceiro de Paulo nas viagens. Preso e ferido em Filipos, cantava louvores à meia-noite.',
    quem: 'Também chamado Silvano, era um líder respeitado da igreja de Jerusalém. Depois que Paulo e Barnabé se separam, Silas vai com Paulo na segunda viagem missionária. Em Filipos, os dois são açoitados e presos. À meia-noite, estão orando e cantando quando um terremoto abre as portas da prisão. Mais tarde, aparece junto com Paulo nas cartas aos tessalonicenses.',
    onde: 'Atos 15-18; 1 Tessalonicenses 1.1; 2 Tessalonicenses 1.1; citado em 1 Pedro 5.12.',
    deus: 'Paulo e Silas adoram a Deus no pior momento, com as costas feridas e os pés presos, e os outros presos ouvem (Atos 16.25). Depois do terremoto, o carcereiro pergunta o que precisa fazer pra ser salvo, e ele e toda a família creem.\n\nSilas trabalhou com Paulo e depois também com Pedro. Era alguém de confiança pros dois.',
  },
  'Simeão e Ana': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Um homem devoto e uma profetisa idosa que esperavam o Messias e o reconheceram num bebê, no templo.',
    quem: 'Duas pessoas de Jerusalém que esperavam o Messias. Deus tinha revelado a Simeão que ele não morreria antes de ver o Messias. Quando Maria e José levam o bebê Jesus ao templo, Simeão pega a criança no colo e louva a Deus. Ana, viúva havia muitos anos, que passava os dias no templo orando e jejuando, começa a falar do menino a todos em Jerusalém que esperavam a vinda do Salvador.',
    onde: 'Lucas 2.22-38.',
    deus: 'Deus honra anos de espera fiel. Duas pessoas comuns, sem cargo nenhum, reconhecem o Messias antes de quase todo o povo.\n\nSimeão anuncia que aquela salvação seria luz pra todos os povos, e não só pra Israel (Lucas 2.32). E avisa Maria que a tristeza, como uma espada, atravessaria a alma dela (Lucas 2.35).',
  },
  'Tiago irmão de Jesus': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Não acreditava no próprio irmão. Depois da ressurreição, virou líder da igreja de Jerusalém.',
    quem: 'Irmão de Jesus que, segundo os evangelhos, não acreditava nele durante o ministério (João 7.5). Depois da ressurreição, Jesus aparece a ele (1 Coríntios 15.7), e Tiago se torna um dos principais líderes da igreja de Jerusalém. A tradição o reconhece como autor da carta de Tiago.',
    onde: 'João 7.5; Atos 15 e 21; 1 Coríntios 15.7; Gálatas 1.19 e 2.9; carta de Tiago.',
    deus: 'Crescer na mesma casa que Jesus não fez Tiago crer. Encontrar Jesus ressuscitado fez. A ressurreição mudou até quem estava mais perto e mais resistente.\n\nNo encontro de Jerusalém, em Atos 15, Tiago ajuda a igreja a decidir como receber os cristãos não judeus sem exigir deles toda a lei judaica. Deus guia a igreja em decisões difíceis por meio da oração, das Escrituras e da conversa entre irmãos.',
    erros: 'Antes da ressurreição, não acreditava em Jesus. Marcos 3.21 conta que a família chegou a achar que Jesus estava fora de si.',
  },
  'Timóteo': {
    sub: 'Igreja primitiva · séc. I',
    resumo: 'Jovem acompanhado de perto por Paulo, que ouviu dele: ninguém faça pouco caso de você porque você ainda é moço.',
    quem: 'Jovem de Listra, filho de mãe judia e pai grego. A mãe, Eunice, e a avó, Loide, ensinaram a ele as Escrituras desde criança (2 Timóteo 1.5 e 3.15). Torna-se companheiro próximo de Paulo, que o chama de filho na fé, e recebe duas cartas com orientações pra cuidar da igreja em Éfeso.',
    onde: 'Atos 16; 1 e 2 Timóteo; citado em Filipenses 2.19-22 e em outras cartas de Paulo.',
    deus: 'A relação entre Paulo e Timóteo mostra o valor de ser acompanhado de perto, por muitos anos, por alguém mais maduro na fé.\n\nPaulo escreve a Timóteo: ninguém faça pouco caso de você porque você ainda é moço, e seja modelo pra eles no amor, na fé e na pureza (1 Timóteo 4.12). E lembra que o Espírito que Deus nos deu não é de covardia, mas de poder, de amor e de equilíbrio (2 Timóteo 1.7).',
  },
  'Tomé': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Ficou famoso pela dúvida, mas foi quem disse uma das frases mais claras da Bíblia sobre Jesus: meu Senhor e meu Deus.',
    quem: 'Um dos doze, também chamado Dídimo, que quer dizer gêmeo. É lembrado principalmente porque não acreditou quando os outros discípulos disseram que tinham visto Jesus ressuscitado. Ele queria ver e tocar as marcas da cruz.',
    onde: 'Mateus 10; Marcos 3; Lucas 6; João 11, 14, 20 e 21; Atos 1.',
    deus: 'O apelido Tomé incrédulo simplifica a história. Tomé pediu a mesma prova que os outros discípulos já tinham recebido quando Jesus apareceu a eles. Jesus volta, mostra as mãos e o lado, e Tomé diz: meu Senhor e meu Deus (João 20.28). É uma das declarações mais claras de toda a Bíblia de que Jesus é Deus.\n\nAntes disso, quando Jesus decidiu voltar pra perto de Jerusalém, onde queriam matá-lo, foi Tomé quem disse: vamos até lá para morrermos com o Mestre (João 11.16). Tomé tinha dúvidas e coragem ao mesmo tempo.',
    erros: 'Não acreditou no testemunho dos outros discípulos sobre a ressurreição sem ver as marcas da cruz. Jesus o atende e diz: felizes são aqueles que não me viram e mesmo assim creram (João 20.29).',
  },
  'Zacarias pai de João Batista': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Sacerdote que duvidou do anjo e ficou sem falar até o nascimento de João. Quando voltou a falar, louvou a Deus.',
    quem: 'Sacerdote casado com Isabel. Estava queimando incenso no templo quando o anjo Gabriel aparece e anuncia que ele e a esposa, já idosos, teriam um filho. Zacarias duvida e fica mudo até o bebê nascer. Quando confirma por escrito que o nome do menino é João, volta a falar e canta uma profecia sobre a vinda do Salvador.',
    onde: 'Lucas 1.',
    deus: 'Deus cumpre a promessa mesmo com a dúvida de Zacarias, e a mudez mostra que a descrença tem consequência. A promessa também era resposta a oração: o anjo diz que o pedido deles tinha sido ouvido (Lucas 1.13).\n\nO cântico de Zacarias (Lucas 1.67-79) liga o nascimento do filho às promessas feitas a Abraão e a Davi. João Batista entra numa história que Deus vinha conduzindo havia séculos.',
    erros: 'Duvidou da palavra do anjo e perguntou como poderia ter certeza daquilo. Por isso ficou sem falar até a promessa se cumprir.',
  },
  'Zaqueu': {
    sub: 'Evangelhos · séc. I',
    resumo: 'Chefe dos cobradores de impostos, baixinho, subiu numa árvore pra ver Jesus. Jesus se convidou pra casa dele.',
    quem: 'Chefe dos cobradores de impostos em Jericó, homem rico e de baixa estatura. Sobe numa árvore, um sicômoro, pra conseguir ver Jesus por cima da multidão. Jesus para, chama Zaqueu pelo nome e diz que precisa ficar na casa dele naquele dia. Zaqueu desce feliz e anuncia que vai dar metade dos bens aos pobres e devolver quatro vezes mais a quem tivesse cobrado demais.',
    onde: 'Lucas 19.1-10.',
    deus: 'O povo reclama porque Jesus vai se hospedar na casa de um homem visto como ladrão e traidor. Jesus resume o que aconteceu: o Filho do Homem veio buscar e salvar o que se havia perdido (Lucas 19.10).\n\nA mudança de Zaqueu aparece em atitudes concretas, com dinheiro devolvido e generosidade. Arrependimento de verdade mexe no bolso e conserta o que dá pra consertar.',
    erros: 'Era chefe dos cobradores de impostos, rico e visto pelo povo como pecador. Ele mesmo admite que pode ter cobrado demais de alguém (Lucas 19.8).',
  },
};
